(() => {
  'use strict';

  const KEYS = {
    session: 'htpNewsroomSession', stories: 'htpNewsroomStories', assignments: 'htpNewsroomAssignmentsV3',
    staff: 'htpNewsroomStaffV3', audit: 'htpNewsroomAudit', media: 'htpNewsroomMediaV3',
    comments: 'htpNewsroomCommentsV3', campaigns: 'htpAdCampaigns', overrides: 'htpStoryOverrides',
    sessions: 'htpNewsroomSessionsV3', notifications: 'htpNewsroomNotificationsV3'
  };
  const HOSPAZ = 'https://healthtimes.co.zw/wp-content/uploads/2025/11/HOSPAZ-hospice-and-palliative-care-assosciation-of-zimbabwe-annual-general-meeting-25-september-2026.jpeg';
  const $ = (s, r=document) => r.querySelector(s);
  const $$ = (s, r=document) => [...r.querySelectorAll(s)];
  const read = (k, f) => { try { const v=localStorage.getItem(k); return v ? JSON.parse(v) : f; } catch { return f; } };
  const write = (k,v) => { try { localStorage.setItem(k, JSON.stringify(v)); } catch {} };
  const esc = (v='') => String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const iso = () => new Date().toISOString();
  const stamp = () => iso().slice(0,16).replace('T',' ');
  const initials = n => String(n||'').split(/\s+/).filter(Boolean).map(x=>x[0]).join('').slice(0,2).toUpperCase() || 'HT';
  const slugify = v => String(v||'').toLowerCase().normalize('NFKD').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,90);

  const CAP = {
    STORY_CREATE:'story.create', STORY_EDIT_OWN:'story.edit_own', STORY_EDIT_ALL:'story.edit_all', STORY_SUBMIT:'story.submit',
    STORY_FACT:'story.fact_check', STORY_HEALTH:'story.health_review', STORY_COPY:'story.copy_edit', STORY_PUBLISH:'story.publish', STORY_CORRECT:'story.correct',
    ASSIGN_CREATE:'assignment.create', ASSIGN_MANAGE:'assignment.manage', PREMIUM_ASSIGN:'premium.assign', PREMIUM_MANAGE:'premium.manage',
    ADS_VIEW:'ads.view', ADS_CREATE:'ads.create', ADS_APPROVE:'ads.approve', SUB_VIEW:'subscriber.view', SUB_MANAGE:'subscriber.manage',
    STAFF_VIEW:'staff.view', STAFF_INVITE:'staff.invite', STAFF_ROLE:'staff.change_role', STAFF_REVOKE:'staff.revoke',
    ANALYTICS:'analytics.view', SETTINGS:'settings.manage', SECURITY:'security.manage', DISTRIBUTION:'distribution.manage', MEDIA:'media.manage'
  };

  const ROLE_CAPS = {
    'Publisher / Owner': Object.values(CAP),
    'Editor-in-Chief':[CAP.STORY_CREATE,CAP.STORY_EDIT_ALL,CAP.STORY_SUBMIT,CAP.STORY_FACT,CAP.STORY_HEALTH,CAP.STORY_COPY,CAP.STORY_PUBLISH,CAP.STORY_CORRECT,CAP.ASSIGN_CREATE,CAP.ASSIGN_MANAGE,CAP.PREMIUM_ASSIGN,CAP.PREMIUM_MANAGE,CAP.ADS_VIEW,CAP.ADS_APPROVE,CAP.SUB_VIEW,CAP.STAFF_VIEW,CAP.STAFF_INVITE,CAP.STAFF_ROLE,CAP.STAFF_REVOKE,CAP.ANALYTICS,CAP.DISTRIBUTION,CAP.MEDIA,CAP.SECURITY],
    'Managing Editor':[CAP.STORY_CREATE,CAP.STORY_EDIT_ALL,CAP.STORY_SUBMIT,CAP.STORY_FACT,CAP.STORY_HEALTH,CAP.STORY_COPY,CAP.STORY_PUBLISH,CAP.STORY_CORRECT,CAP.ASSIGN_CREATE,CAP.ASSIGN_MANAGE,CAP.PREMIUM_ASSIGN,CAP.STAFF_VIEW,CAP.ANALYTICS,CAP.DISTRIBUTION,CAP.MEDIA],
    'Section Editor':[CAP.STORY_CREATE,CAP.STORY_EDIT_ALL,CAP.STORY_SUBMIT,CAP.STORY_FACT,CAP.STORY_COPY,CAP.ASSIGN_CREATE,CAP.ASSIGN_MANAGE,CAP.PREMIUM_ASSIGN,CAP.ANALYTICS,CAP.DISTRIBUTION,CAP.MEDIA],
    'News Editor':[CAP.STORY_CREATE,CAP.STORY_EDIT_ALL,CAP.STORY_SUBMIT,CAP.STORY_FACT,CAP.STORY_COPY,CAP.ASSIGN_CREATE,CAP.ASSIGN_MANAGE,CAP.ANALYTICS,CAP.DISTRIBUTION,CAP.MEDIA],
    'Reporter / Journalist':[CAP.STORY_CREATE,CAP.STORY_EDIT_OWN,CAP.STORY_SUBMIT,CAP.MEDIA],
    'Health / Science Editor':[CAP.STORY_EDIT_ALL,CAP.STORY_HEALTH,CAP.STORY_SUBMIT,CAP.ANALYTICS],
    'Fact Checker':[CAP.STORY_EDIT_ALL,CAP.STORY_FACT,CAP.STORY_SUBMIT],
    'Copy Editor':[CAP.STORY_EDIT_ALL,CAP.STORY_COPY,CAP.STORY_SUBMIT],
    'Multimedia Editor':[CAP.MEDIA,CAP.STORY_EDIT_ALL],
    'Social Editor':[CAP.DISTRIBUTION,CAP.ANALYTICS],
    'Newsletter Editor':[CAP.DISTRIBUTION,CAP.ANALYTICS,CAP.SUB_VIEW],
    'Commercial Manager':[CAP.ADS_VIEW,CAP.ADS_CREATE,CAP.ADS_APPROVE,CAP.SUB_VIEW,CAP.SUB_MANAGE,CAP.ANALYTICS,CAP.PREMIUM_MANAGE],
    'Subscriber Manager':[CAP.SUB_VIEW,CAP.SUB_MANAGE,CAP.ANALYTICS],
    'Analyst':[CAP.ANALYTICS]
  };

  const ACCOUNTS = {
    publisher:{password:'HealthTimes#Publisher26',name:'Publisher Office',email:'publisher@healthtimes.co.zw',role:'Publisher / Owner',desk:'Executive',beat:'Organisation',country:'Zimbabwe'},
    editor:{password:'HealthTimes#Editor26',name:'Michael Gwarisa',email:'editor@healthtimes.co.zw',role:'Editor-in-Chief',desk:'Global Health',beat:'Policy & Health Systems',country:'Zimbabwe'},
    reporter:{password:'HealthTimes#Reporter26',name:'Kuda Pembere',email:'reporter@healthtimes.co.zw',role:'Reporter / Journalist',desk:'Africa',beat:'Public Health',country:'Zimbabwe'},
    audience:{password:'HealthTimes#Audience26',name:'Audience Desk',email:'audience@healthtimes.co.zw',role:'Newsletter Editor',desk:'Audience',beat:'Distribution',country:'Zimbabwe'},
    commercial:{password:'HealthTimes#Commercial26',name:'Commercial Desk',email:'commercial@healthtimes.co.zw',role:'Commercial Manager',desk:'Commercial',beat:'Advertising & Membership',country:'Zimbabwe'}
  };

  const DESKS=['Global Health','Africa','Southern Africa','East Africa','West Africa','Central Africa','North Africa','Zimbabwe','Research','Policy','Investigations','Health Business','Audience','Commercial'];
  const REGIONS=['Global','Africa','Southern Africa','East Africa','West Africa','Central Africa','North Africa','Zimbabwe'];
  const WORKFLOW=['Pitch','Approved','Assigned','Reporting','Draft','Submitted','Fact check','Health / Science review','Copy edit','Editor review','Ready','Scheduled','Published','Updated / Corrected','Archived'];
  const titleToId={
    'Parliament Probes NatPharm Over Zimbabwe’s Medicine Supply Chain':'natpharm-supply-chain',
    'Harare STI Cases Fall Below 2,000 Per Quarter, NAC Says':'harare-sti-cases',
    'Healthathon 3.0: What Zimbabwe’s Health Innovation Challenge Is Telling Us':'healthathon-innovation',
    'Zimbabwe Drops National Health Insurance Name, Unveils Tax-Funded Healthcare Provision Programme':'healthcare-provision-programme'
  };

  const initialStories=[
    {id:'s1',title:'Parliament Probes NatPharm Over Zimbabwe’s Medicine Supply Chain',standfirst:'Parliament resumes scrutiny of medicines procurement and distribution.',body:'Parliament has resumed its inquiry into Zimbabwe’s medicines supply system, focusing on procurement, storage, distribution and whether public investment is translating into reliable supplies for patients.',sources:'Parliamentary Portfolio Committee on Health and Child Care',notes:'Primary documents verified.',section:'Health Policy',desk:'Policy',country:'Zimbabwe',region:'Zimbabwe',topic:'Medicines',premium:false,owner:'editor',author:'Michael Gwarisa',editor:'editor',factChecker:'',status:'Published',deadline:'',schedule:'',updated:'2026-09-07 08:30',seoTitle:'Parliament probes NatPharm medicine supply chain',metaDescription:'HealthTimes reporting on Parliament scrutiny of Zimbabwe medicine supply.',slug:'natpharm-supply-chain',adSetting:'Standard',distribution:{homepage:true,breaking:false,newsletter:true,whatsapp:true,push:false},versions:[]},
    {id:'s2',title:'Harare STI Cases Fall Below 2,000 Per Quarter, NAC Says',standfirst:'NAC reports a decline while warning of the continued burden among young women.',body:'Health authorities say the trend is encouraging but requires careful interpretation and continued prevention investment.',sources:'National AIDS Council briefing',notes:'Confirm age-disaggregated figures before next update.',section:'Public Health',desk:'Africa',country:'Zimbabwe',region:'Zimbabwe',topic:'HIV/AIDS',premium:false,owner:'reporter',author:'Kuda Pembere',editor:'editor',factChecker:'',status:'Published',deadline:'',schedule:'',updated:'2026-09-07 09:10',seoTitle:'Harare STI cases fall, NAC says',metaDescription:'NAC reports lower STI cases in Harare.',slug:'harare-sti-cases',adSetting:'Standard',distribution:{homepage:true,breaking:false,newsletter:true,whatsapp:true,push:false},versions:[]},
    {id:'s3',title:'Healthathon 3.0: What Zimbabwe’s Health Innovation Challenge Is Telling Us',standfirst:'Analysis of the expanding health-innovation ecosystem.',body:'Healthathon 3.0 is exposing a growing pipeline of locally grounded health innovation and a need for stronger pathways from prototype to health-system adoption.',sources:'Healthathon programme and participant interviews',notes:'Analysis piece.',section:'Opinion & Analysis',desk:'Research',country:'Zimbabwe',region:'Africa',topic:'Innovation',premium:false,owner:'editor',author:'Michael Gwarisa',editor:'editor',factChecker:'',status:'Published',deadline:'',schedule:'',updated:'2026-09-07 12:05',seoTitle:'Healthathon 3.0 health innovation analysis',metaDescription:'HealthTimes analysis of Zimbabwe health innovation.',slug:'healthathon-innovation',adSetting:'Standard',distribution:{homepage:true,breaking:false,newsletter:true,whatsapp:false,push:false},versions:[]},
    {id:'s4',title:'Medicine Supply Dashboard: What the NatPharm Inquiry Should Measure Next',standfirst:'A proposed accountability framework for tracking medicines from financing to facilities.',body:'This research note proposes a practical dashboard for following medicine availability, procurement lead times, stock-outs and financing through the public supply chain.',sources:'Parliamentary evidence; NatPharm public documents; procurement literature',notes:'Sources verified. Awaiting final approval.',section:'Health Policy',desk:'Policy',country:'Zimbabwe',region:'Africa',topic:'Medicines',premium:true,owner:'editor',author:'Michael Gwarisa',editor:'editor',factChecker:'factchecker',status:'Ready',deadline:'2026-09-09T16:00',schedule:'',updated:'2026-09-09 08:40',seoTitle:'Medicine supply dashboard for Zimbabwe',metaDescription:'A HealthTimes Premium accountability framework for medicines.',slug:'medicine-supply-dashboard',adSetting:'Reduced',distribution:{homepage:false,breaking:false,newsletter:true,whatsapp:false,push:false},versions:[]},
    {id:'s5',title:'Community Prevention Follow-up: What Harare’s STI Trend Does Not Yet Tell Us',standfirst:'A follow-up examining age, reporting periods and prevention evidence.',body:'The apparent decline is important, but aggregate counts do not answer questions about age, gender, geography or testing intensity.',sources:'NAC briefing; city health data request pending',notes:'Needs data-context check.',section:'Public Health',desk:'Africa',country:'Zimbabwe',region:'Zimbabwe',topic:'HIV/AIDS',premium:true,owner:'reporter',author:'Kuda Pembere',editor:'editor',factChecker:'factchecker',status:'Submitted',deadline:'2026-09-09T14:00',schedule:'',updated:'2026-09-09 09:05',seoTitle:'What Harare STI trends do not yet tell us',metaDescription:'HealthTimes analysis of STI trend interpretation.',slug:'harare-sti-trend-analysis',adSetting:'Reduced',distribution:{homepage:false,breaking:false,newsletter:false,whatsapp:false,push:false},versions:[]},
    {id:'s6',title:'Weekly Africa Outbreak Watch',standfirst:'A developing regional health surveillance briefing.',body:'This week’s watch follows outbreak updates across the continent and highlights signals that require further verification.',sources:'Africa CDC; WHO disease outbreak news',notes:'Add Africa CDC update.',section:'Africa',desk:'Africa',country:'Multiple',region:'Africa',topic:'Outbreaks',premium:false,owner:'reporter',author:'Kuda Pembere',editor:'editor',factChecker:'',status:'Draft',deadline:'2026-09-09T18:00',schedule:'',updated:'2026-09-09 09:30',seoTitle:'Weekly Africa outbreak watch',metaDescription:'HealthTimes weekly outbreak reporting across Africa.',slug:'africa-outbreak-watch',adSetting:'Standard',distribution:{homepage:false,breaking:false,newsletter:true,whatsapp:true,push:false},versions:[]},
    {id:'s7',title:'National Health Strategy: Implementation Tracker',standfirst:'A living tracker of implementation commitments under the national strategy.',body:'The tracker follows milestones, financing commitments and service-delivery indicators against stated policy goals.',sources:'Ministry strategy; budget documents',notes:'Fact checker to verify milestones.',section:'Health Policy',desk:'Policy',country:'Zimbabwe',region:'Zimbabwe',topic:'Health Systems',premium:true,owner:'editor',author:'Michael Gwarisa',editor:'editor',factChecker:'factchecker',status:'Fact check',deadline:'2026-09-10T12:00',schedule:'',updated:'2026-09-09 10:00',seoTitle:'National health strategy implementation tracker',metaDescription:'HealthTimes Premium policy implementation tracker.',slug:'national-health-strategy-tracker',adSetting:'Reduced',distribution:{homepage:false,breaking:false,newsletter:false,whatsapp:false,push:false},versions:[]},
    {id:'s8',title:'Friday HealthTimes Weekly',standfirst:'The week’s essential health reporting in one concise edition.',body:'Editorial briefing assembly.',sources:'Published HealthTimes stories',notes:'Scheduled after final story selection.',section:'Health News',desk:'Audience',country:'Global',region:'Global',topic:'Briefing',premium:false,owner:'audience',author:'Audience Desk',editor:'editor',factChecker:'',status:'Scheduled',deadline:'2026-09-11T10:00',schedule:'2026-09-11T12:00',updated:'2026-09-09 10:10',seoTitle:'HealthTimes Weekly',metaDescription:'Weekly HealthTimes briefing.',slug:'healthtimes-weekly',adSetting:'Standard',distribution:{homepage:false,breaking:false,newsletter:true,whatsapp:true,push:false},versions:[]}
  ];

  const initialAssignments=[
    {id:'a1',title:'Africa CDC outbreak surveillance update',reporter:'reporter',desk:'Africa',deadline:'2026-09-09T17:00',priority:'High',editor:'editor',status:'Reporting',notes:'Confirm cut-off time and compare with WHO notices.'},
    {id:'a2',title:'Malaria financing after donor transition',reporter:'reporter',desk:'Africa',deadline:'2026-09-10T14:00',priority:'Urgent',editor:'editor',status:'Assigned',notes:'Interview programme manager and financing specialist.'},
    {id:'a3',title:'HealthTimes global citations strategy explainer',reporter:'editor',desk:'Research',deadline:'2026-09-12T12:00',priority:'Normal',editor:'publisher',status:'Drafting',notes:'Frame HealthTimes research for international referencing.'},
    {id:'a4',title:'Friday HealthTimes Weekly assembly',reporter:'audience',desk:'Audience',deadline:'2026-09-11T10:00',priority:'High',editor:'editor',status:'Drafting',notes:'Select five essential stories and one Premium research note.'}
  ];

  const initialStaff=[
    {username:'publisher',name:'Publisher Office',email:'publisher@healthtimes.co.zw',role:'Publisher / Owner',desk:'Executive',beat:'Organisation',country:'Zimbabwe',region:'Global',status:'Active',editor:'',lastLogin:'Today 08:15',passwordChange:false,mfa:'Ready'},
    {username:'editor',name:'Michael Gwarisa',email:'editor@healthtimes.co.zw',role:'Editor-in-Chief',desk:'Global Health',beat:'Policy & Health Systems',country:'Zimbabwe',region:'Global',status:'Active',editor:'',lastLogin:'Today 09:02',passwordChange:false,mfa:'Ready'},
    {username:'reporter',name:'Kuda Pembere',email:'reporter@healthtimes.co.zw',role:'Reporter / Journalist',desk:'Africa',beat:'Public Health',country:'Zimbabwe',region:'Southern Africa',status:'Active',editor:'editor',lastLogin:'Today 08:47',passwordChange:false,mfa:'Pending'},
    {username:'factchecker',name:'Tariro Ncube',email:'factcheck@healthtimes.co.zw',role:'Fact Checker',desk:'Research',beat:'Evidence verification',country:'Zimbabwe',region:'Africa',status:'Active',editor:'editor',lastLogin:'Yesterday 16:42',passwordChange:false,mfa:'Ready'},
    {username:'science',name:'Dr Nyasha Moyo',email:'science@healthtimes.co.zw',role:'Health / Science Editor',desk:'Research',beat:'Medical evidence',country:'South Africa',region:'Africa',status:'Active',editor:'editor',lastLogin:'Yesterday 15:20',passwordChange:false,mfa:'Ready'},
    {username:'audience',name:'Audience Desk',email:'audience@healthtimes.co.zw',role:'Newsletter Editor',desk:'Audience',beat:'Distribution',country:'Zimbabwe',region:'Global',status:'Active',editor:'editor',lastLogin:'Today 09:10',passwordChange:false,mfa:'Ready'},
    {username:'commercial',name:'Commercial Desk',email:'commercial@healthtimes.co.zw',role:'Commercial Manager',desk:'Commercial',beat:'Advertising & Membership',country:'Zimbabwe',region:'Global',status:'Active',editor:'publisher',lastLogin:'Today 08:30',passwordChange:false,mfa:'Ready'}
  ];

  const initialMedia=[
    {id:'m1',filename:'hospaz-agm-2026.jpeg',type:'Image',caption:'HOSPAZ Annual General Meeting campaign',credit:'HOSPAZ',copyright:'Advertiser supplied',source:'HealthTimes source site',uploadedBy:'Commercial Desk',usedIn:'Advertising campaign',date:'2026-09-01'},
    {id:'m2',filename:'natpharm-parliament.jpg',type:'Image',caption:'Parliamentary health committee coverage',credit:'HealthTimes',copyright:'HealthTimes',source:'Editorial library',uploadedBy:'Michael Gwarisa',usedIn:'NatPharm story',date:'2026-09-07'},
    {id:'m3',filename:'healthathon-3.jpg',type:'Image',caption:'Healthathon participants',credit:'HealthTimes',copyright:'HealthTimes',source:'Editorial library',uploadedBy:'Kuda Pembere',usedIn:'Healthathon 3.0',date:'2026-09-07'},
    {id:'m4',filename:'africa-cdc-briefing.pdf',type:'Document',caption:'Africa CDC weekly surveillance briefing',credit:'Africa CDC',copyright:'Source document',source:'Africa CDC',uploadedBy:'Kuda Pembere',usedIn:'Outbreak Watch',date:'2026-09-09'}
  ];

  const initialCampaigns=[{id:'hospaz-agm-2026',advertiser:'HOSPAZ',name:'HOSPAZ Annual General Meeting',creative:HOSPAZ,destination:'https://healthtimes.co.zw/',placement:['masthead','home-infeed','article'],start:'2026-09-01',end:'2026-09-25',status:'Active',review:'Approved',label:'Advertisement',impressions:0,clicks:0}];

  const NAV=[
    ['My Newsroom',[['overview','Overview','⌂'],['my-assignments','My assignments','✓'],['my-stories','My stories','▤'],['saved','Saved','☆']]],
    ['Editorial',[['stories','Stories','▤','editorial'],['assignments','Assignments','✓',CAP.ASSIGN_MANAGE],['review','Review Queue','◫','review'],['calendar','Editorial Calendar','□','editorial'],['breaking','Breaking News','!','editorial'],['corrections','Corrections','↺','editorial']]],
    ['Content',[['media','Media Library','▧',CAP.MEDIA],['authors','Authors','◎','editorial'],['topics','Topics','⌗','editorial'],['regions','Countries & regions','◌','editorial'],['sources','Research / Sources','≡','editorial'],['archive','Archive','▱','editorial']]],
    ['Distribution',[['homepage','Homepage','⌂',CAP.DISTRIBUTION],['newsletter','Newsletters','✉',CAP.DISTRIBUTION],['whatsapp','WhatsApp','◉',CAP.DISTRIBUTION],['social','Social','↗',CAP.DISTRIBUTION],['push','Push alerts','●',CAP.DISTRIBUTION]]],
    ['Intelligence',[['analytics','Analytics','↗',CAP.ANALYTICS],['trending','Trending','↗',CAP.ANALYTICS],['seo','SEO','⌕','editorial'],['citations','Citations & Impact','§',CAP.ANALYTICS],['ai','AI Desk','✦','editorial']]],
    ['Commercial',[['premium','Premium','◆','premium'],['subscribers','Subscribers','♙',CAP.SUB_VIEW],['advertising','Advertising','▣',CAP.ADS_VIEW]]],
    ['Organisation',[['staff','Staff & Access','♟',CAP.STAFF_VIEW],['roles','Roles & Permissions','⚿',CAP.STAFF_VIEW],['audit','Audit Log','≣','admin']]],
    ['System',[['settings','Settings','⚙',CAP.SETTINGS],['integrations','Integrations','⌁','admin'],['security','Security','⌾','security']]]
  ];

  let active='overview', editingStoryId=null, autosaveTimer=null, pendingConfirm=null;
  function ensureSeed(){ if(!read(KEYS.stories,null))write(KEYS.stories,initialStories); if(!read(KEYS.assignments,null))write(KEYS.assignments,initialAssignments); if(!read(KEYS.staff,null))write(KEYS.staff,initialStaff); if(!read(KEYS.media,null))write(KEYS.media,initialMedia); if(!read(KEYS.campaigns,null))write(KEYS.campaigns,initialCampaigns); if(!read(KEYS.comments,null))write(KEYS.comments,{}); if(!read(KEYS.audit,null))write(KEYS.audit,[]); }
  function getStories(){ensureSeed();return read(KEYS.stories,[])} function setStories(v){write(KEYS.stories,v)}
  function getAssignments(){ensureSeed();return read(KEYS.assignments,[])} function setAssignments(v){write(KEYS.assignments,v)}
  function getStaff(){ensureSeed();return read(KEYS.staff,[])} function setStaff(v){write(KEYS.staff,v)}
  function getMedia(){ensureSeed();return read(KEYS.media,[])}
  function caps(role){return new Set(ROLE_CAPS[role]||[])} function has(cap){return caps(currentUser()?.role).has(cap)}
  function staffRecord(username){return getStaff().find(x=>x.username===username)}
  function currentUser(){const s=read(KEYS.session,null);if(!s?.username||!ACCOUNTS[s.username])return null;const base=ACCOUNTS[s.username], staff=staffRecord(s.username);if(staff?.status==='Revoked'||staff?.status==='Deactivated'||staff?.status==='Suspended')return null;return {...base,...staff,username:s.username,initials:initials(staff?.name||base.name)};}
  function isEditor(){return has(CAP.STORY_EDIT_ALL)||has(CAP.STORY_PUBLISH)||has(CAP.ASSIGN_MANAGE)}
  function canEditStory(s){const u=currentUser();return !!u && (has(CAP.STORY_EDIT_ALL)||(has(CAP.STORY_EDIT_OWN)&&s.owner===u.username));}
  function canModule(id,rule){if(!currentUser())return false;if(!rule)return true;if(rule==='editorial')return has(CAP.STORY_EDIT_ALL)||has(CAP.STORY_CREATE)||has(CAP.STORY_FACT)||has(CAP.STORY_HEALTH)||has(CAP.STORY_COPY);if(rule==='review')return has(CAP.STORY_FACT)||has(CAP.STORY_HEALTH)||has(CAP.STORY_COPY)||has(CAP.STORY_PUBLISH);if(rule==='premium')return has(CAP.PREMIUM_ASSIGN)||has(CAP.PREMIUM_MANAGE);if(rule==='admin')return has(CAP.STAFF_VIEW)||has(CAP.SETTINGS)||has(CAP.SECURITY);if(rule==='security')return has(CAP.SECURITY)||!!currentUser();return has(rule);}
  function audit(action){const u=currentUser();const list=read(KEYS.audit,[]);list.unshift({at:iso(),user:u?.name||'System',role:u?.role||'System',action});write(KEYS.audit,list.slice(0,150));}
  function toast(msg){const el=$('[data-newsroom-toast]');if(!el)return;el.textContent=msg;el.classList.add('show');clearTimeout(el._t);el._t=setTimeout(()=>el.classList.remove('show'),2200);}
  function syncPremium(story){const id=titleToId[story.title]||story.slug; if(!id)return; const o=read(KEYS.overrides,{});o[id]={...(o[id]||{}),premium:!!story.premium,updatedAt:iso(),source:'newsroom'};write(KEYS.overrides,o);}

  function login(username,password){ensureSeed();const key=String(username||'').trim().toLowerCase();const a=ACCOUNTS[key], staff=staffRecord(key);if(!a||a.password!==password||['Suspended','Deactivated','Revoked'].includes(staff?.status))return false;write(KEYS.session,{username:key,signedInAt:iso(),sessionId:`session-${Date.now()}`});const sessions=read(KEYS.sessions,{});sessions[key]=[{id:`current-${Date.now()}`,device:'Current browser',location:'Active session',lastActive:'Now',current:true},...(sessions[key]||[]).filter(x=>!x.current).slice(0,2)];write(KEYS.sessions,sessions);staff.lastLogin='Now';setStaff(getStaff().map(x=>x.username===key?staff:x));audit(`${a.name} signed in to HealthTimes Newsroom`);return true;}
  function logout(){const u=currentUser();if(u)audit(`${u.name} signed out`);localStorage.removeItem(KEYS.session);location.reload();}

  function init(){ensureSeed();bindGlobal();const u=currentUser();if(!u){$('[data-login-view]').hidden=false;$('[data-newsroom-app]').hidden=true;return;}$('[data-login-view]').hidden=true;$('[data-newsroom-app]').hidden=false;renderUser();renderNav();showModule('overview');}

  function renderUser(){const u=currentUser();$('[data-user-mini]').innerHTML=`<div class="nr-user-mini-row"><span class="nr-avatar">${esc(u.initials)}</span><span><strong>${esc(u.name)}</strong><small>${esc(u.role)}</small></span><button type="button" data-sign-out aria-label="Sign out">↪</button></div>`;$('[data-user-menu]').textContent=u.initials;$('[data-topline]').textContent=`${u.name} · ${u.role}`;}
  function navCount(id){const u=currentUser(), stories=getStories(), assignments=getAssignments();if(id==='my-assignments')return assignments.filter(a=>a.reporter===u.username&&!['Complete'].includes(a.status)).length;if(id==='my-stories')return stories.filter(s=>s.owner===u.username&&!['Archived'].includes(s.status)).length;if(id==='review')return stories.filter(s=>['Submitted','Fact check','Health / Science review','Copy edit','Editor review','Ready'].includes(s.status)).length;if(id==='corrections')return stories.filter(s=>s.status==='Updated / Corrected').length;if(id==='premium')return stories.filter(s=>s.premium).length;return 0;}
  function renderNav(){const nav=$('[data-newsroom-nav]');nav.innerHTML=NAV.map(([group,items])=>{const visible=items.filter(([id,, ,rule])=>canModule(id,rule));if(!visible.length)return'';return `<section class="nr-nav-group"><div class="nr-nav-label">${esc(group)}</div>${visible.map(([id,label,icon])=>`<button type="button" data-module="${id}" ${id==='advertising'?'data-v21-module="ads"':''} class="${active===id?'active':''}"><span class="nr-nav-icon">${icon}</span><span>${esc(label)}</span>${navCount(id)?`<span class="nr-nav-count">${navCount(id)}</span>`:''}</button>`).join('')}</section>`}).join('');}
  function setCrumb(label){$('[data-breadcrumb]').textContent=label;}
  function head(title,copy,actions=''){return `<div class="nr-workspace-head"><div><span class="nr-kicker">HealthTimes Newsroom</span><h1>${esc(title)}</h1><p>${esc(copy)}</p></div><div class="nr-workspace-actions">${actions}</div></div>`;}
  function stat(label,value,copy,accent='teal'){return `<article class="nr-stat nr-accent-${accent}"><span class="nr-stat-label">${esc(label)}</span><strong>${esc(value)}</strong><small>${esc(copy)}</small></article>`;}
  function status(s){return `<span class="nr-status" data-status="${esc(s)}">${esc(s)}</span>`;}
  function button(label,attr='',cls='nr-secondary'){return `<button type="button" class="${cls}" ${attr}>${esc(label)}</button>`;}

  function showModule(id){const item=NAV.flatMap(g=>g[1]).find(x=>x[0]===id);if(!item||!canModule(id,item[3])){toast('This workspace is not available to your role.');return;}active=id;renderNav();setCrumb(item[1]);const renderers={overview:renderOverview,'my-assignments':renderMyAssignments,'my-stories':renderMyStories,saved:renderSaved,stories:renderStories,assignments:renderAssignments,review:renderReview,calendar:renderCalendar,breaking:renderBreaking,corrections:renderCorrections,media:renderMedia,authors:renderAuthors,topics:renderTopics,regions:renderRegions,sources:renderSources,archive:renderArchive,homepage:renderHomepage,newsletter:renderNewsletter,whatsapp:renderWhatsApp,social:renderSocial,push:renderPush,analytics:renderAnalytics,trending:renderTrending,seo:renderSEO,citations:renderCitations,ai:renderAI,premium:renderPremium,subscribers:renderSubscribers,advertising:renderAdvertising,staff:renderStaff,roles:renderRoles,audit:renderAudit,settings:renderSettings,integrations:renderIntegrations,security:renderSecurity};$('[data-workspace]').innerHTML=(renderers[id]||renderOverview)();}

  function roleDashboard(){const role=currentUser().role;if(role==='Reporter / Journalist')return renderReporterDashboard();if(role==='Commercial Manager')return renderCommercialDashboard();if(role==='Newsletter Editor')return renderAudienceDashboard();if(role==='Publisher / Owner')return renderPublisherDashboard();return renderEditorDashboard();}
  function renderOverview(){return roleDashboard();}
  function renderReporterDashboard(){const u=currentUser(), stories=getStories().filter(s=>s.owner===u.username), assignments=getAssignments().filter(a=>a.reporter===u.username), due=assignments.filter(a=>new Date(a.deadline).toDateString()===new Date().toDateString()), drafts=stories.filter(s=>['Draft','Reporting','Assigned'].includes(s.status)), waiting=stories.filter(s=>['Submitted','Fact check','Editor review'].includes(s.status));return `${head('My Newsroom','Your assignments, drafts, deadlines and editorial feedback in one working view.',has(CAP.STORY_CREATE)?button('＋ New story','data-quick-create','nr-primary'):'')}
  <div class="nr-grid nr-grid-4">${stat('Active assignments',assignments.filter(a=>a.status!=='Complete').length,'Stories currently assigned to you','teal')}${stat('Due today',due.length,'Deadlines requiring attention','red')}${stat('Drafts',drafts.length,'Working copy not yet submitted','blue')}${stat('Waiting for editor',waiting.length,'Submitted or in review','amber')}</div>
  <div class="nr-dashboard-columns"><div class="nr-dashboard-stack"><section class="nr-panel"><div class="nr-panel-head"><div><h2>My assignments</h2><p>Priority work and deadlines</p></div><button data-module-jump="my-assignments">Open desk →</button></div><ul class="nr-list">${assignments.slice(0,5).map(a=>assignmentList(a)).join('')||emptyRow('No active assignments')}</ul></section><section class="nr-panel"><div class="nr-panel-head"><div><h2>My stories</h2><p>Drafting, review and publication state</p></div><button data-module-jump="my-stories">All stories →</button></div><ul class="nr-list">${stories.slice(0,6).map(s=>storyList(s)).join('')}</ul></section></div><div class="nr-dashboard-stack">${todayPanel()}${notificationPanel()}${personalPerformancePanel(stories)}</div></div>`;}
  function renderEditorDashboard(){const stories=getStories(), assignments=getAssignments(), review=stories.filter(s=>['Submitted','Fact check','Health / Science review','Copy edit','Editor review','Ready'].includes(s.status)), overdue=assignments.filter(a=>new Date(a.deadline)<new Date()&&a.status!=='Complete'), ready=stories.filter(s=>['Ready','Scheduled'].includes(s.status)), corrections=stories.filter(s=>s.status==='Updated / Corrected');return `${head('Newsroom today','Review priorities, deadlines, publishing readiness and desk activity.',button('＋ Assignment','data-open-assignment','nr-secondary')+button('＋ New story','data-quick-create','nr-primary'))}<div class="nr-grid nr-grid-4">${stat('Needs review',review.length,'Editorial or verification action','amber')}${stat('Ready to publish',ready.length,'Ready or scheduled work','green')}${stat('Overdue assignments',overdue.length,'Past deadline and incomplete','red')}${stat('Corrections waiting',corrections.length,'Updates requiring publication','blue')}</div><div class="nr-dashboard-columns"><div class="nr-dashboard-stack"><section class="nr-panel"><div class="nr-panel-head"><div><h2>Review queue</h2><p>Work requiring an editorial decision</p></div><button data-module-jump="review">Open queue →</button></div>${review.slice(0,6).map(reviewCard).join('')||empty('Review queue is clear')}</section><section class="nr-panel"><div class="nr-panel-head"><div><h2>Desk activity</h2><p>Current working inventory by desk</p></div></div>${deskActivity()}</section></div><div class="nr-dashboard-stack">${todayPanel()}${trendingPanel()}${publicationPulse()}</div></div>`;}
  function renderPublisherDashboard(){const stories=getStories(),staff=getStaff(), campaigns=read(KEYS.campaigns,initialCampaigns),active=staff.filter(s=>s.status==='Active').length;return `${head('Publisher overview','Organisation-wide editorial, commercial, staff and security context.',button('View audit','data-module-jump="audit"','nr-secondary')+button('Invite staff','data-open-invite','nr-primary'))}<div class="nr-grid nr-grid-4">${stat('Editorial inventory',stories.length,'Stories across all workflow states','teal')}${stat('Active staff',active,'Newsroom accounts currently active','blue')}${stat('Premium research',stories.filter(s=>s.premium).length,'Stories under Premium governance','amber')}${stat('Active campaigns',campaigns.filter(c=>c.status==='Active').length,'Commercial inventory currently running','green')}</div><div class="nr-dashboard-columns"><div class="nr-dashboard-stack"><section class="nr-panel"><div class="nr-panel-head"><div><h2>Operating health</h2><p>Publication work that needs attention</p></div></div>${deskActivity()}</section><section class="nr-panel"><div class="nr-panel-head"><div><h2>Staff & access</h2><p>Current organisation profile</p></div><button data-module-jump="staff">Manage →</button></div><div class="nr-staff-card-grid">${staff.slice(0,6).map(personCard).join('')}</div></section></div><div class="nr-dashboard-stack">${publicationPulse()}${commercialPulse()}${securityPulse()}</div></div>`;}
  function renderCommercialDashboard(){const campaigns=read(KEYS.campaigns,initialCampaigns), stories=getStories(), premium=stories.filter(s=>s.premium);return `${head('Commercial workspace','Advertising, Premium product and subscriber operations — separated from editorial copy.',button('Advertising','data-module-jump="advertising"','nr-primary'))}<div class="nr-grid nr-grid-4">${stat('Active campaigns',campaigns.filter(c=>c.status==='Active').length,'Paid inventory currently running','teal')}${stat('Scheduled campaigns',campaigns.filter(c=>c.status==='Scheduled').length,'Upcoming commercial inventory','blue')}${stat('Premium stories',premium.length,'Current Premium publishing inventory','amber')}${stat('Ad review pending',campaigns.filter(c=>c.review==='Pending').length,'Campaigns needing approval','red')}</div><div class="nr-dashboard-columns"><section class="nr-panel"><div class="nr-panel-head"><div><h2>Campaign inventory</h2><p>Commercial work without editorial permissions</p></div><button data-module-jump="advertising">Manage →</button></div>${campaignTable(campaigns)}</section><div class="nr-dashboard-stack">${commercialPulse()}${subscriberPulse()}</div></div>`;}
  function renderAudienceDashboard(){return `${head('Audience desk','Briefings, WhatsApp, social distribution and reader relationship work.',button('Build briefing','data-module-jump="newsletter"','nr-primary'))}<div class="nr-grid nr-grid-4">${stat('Scheduled editions','2','Weekly + Premium intelligence','teal')}${stat('Stories selected','7','Across active briefing drafts','blue')}${stat('WhatsApp queue','3','Items awaiting distribution','amber')}${stat('Reader channels','3','Email · WhatsApp · browser','green')}</div><div class="nr-dashboard-columns"><div class="nr-dashboard-stack">${distributionQueue()}${todayPanel()}</div><div class="nr-dashboard-stack">${audienceTopicPanel()}${notificationPanel()}</div></div>`;}

  function storyList(s){return `<li class="nr-list-item"><div><strong>${esc(s.title)}</strong><p>${esc(s.desk)} · ${esc(s.premium?'Premium':'Public')} · Updated ${esc(s.updated)}</p></div><div class="nr-list-actions">${status(s.status)}${canEditStory(s)?button('Open',`data-open-story="${esc(s.id)}"`):''}</div></li>`;}
  function assignmentList(a){const overdue=new Date(a.deadline)<new Date()&&a.status!=='Complete';return `<li class="nr-list-item"><div><strong>${esc(a.title)}</strong><p>${esc(a.desk)} · Due ${new Date(a.deadline).toLocaleString()} · ${esc(a.priority)}</p></div><div class="nr-list-actions">${status(overdue?'Overdue':a.status)}${a.reporter===currentUser().username?button('Update',`data-assignment-progress="${esc(a.id)}"`):''}</div></li>`;}
  function reviewCard(s){return `<article class="nr-queue-card"><div class="nr-queue-top"><div><h3>${esc(s.title)}</h3><p>${esc(s.author)} · ${esc(s.desk)} · ${esc(s.premium?'Premium':'Public')} · Updated ${esc(s.updated)}</p></div>${status(s.status)}</div><div class="nr-queue-meta">${button('Open review',`data-open-story="${esc(s.id)}"`,'nr-secondary')}${nextReviewButton(s)}</div></article>`;}
  function nextReviewButton(s){if(!isEditor())return'';const next={'Submitted':'Fact check','Fact check':'Health / Science review','Health / Science review':'Copy edit','Copy edit':'Editor review','Editor review':'Ready','Ready':'Published'}[s.status];return next?button(next==='Published'?'Publish':`Move to ${next}`,`data-transition-story="${esc(s.id)}" data-next="${esc(next)}"`,'nr-primary'):'';}
  function emptyRow(text){return `<li class="nr-empty"><strong>${esc(text)}</strong></li>`;} function empty(text){return `<div class="nr-empty"><strong>${esc(text)}</strong><p>There is nothing waiting here right now.</p></div>`;}
  function todayPanel(){return `<section class="nr-panel"><div class="nr-panel-head"><div><h2>Today</h2><p>Editorial agenda</p></div><button data-module-jump="calendar">Calendar →</button></div><div class="nr-calendar"><div class="nr-calendar-time">09:00</div><div class="nr-calendar-event" data-kind="Meeting"><strong>Editorial conference</strong><span>Global + Africa desks</span></div><div class="nr-calendar-time">12:00</div><div class="nr-calendar-event" data-kind="Deadline"><strong>STI analysis review</strong><span>Editor deadline</span></div><div class="nr-calendar-time">15:30</div><div class="nr-calendar-event" data-kind="Briefing"><strong>WhatsApp briefing lock</strong><span>Audience Desk</span></div></div></section>`;}
  function notificationPanel(){return `<section class="nr-panel"><div class="nr-panel-head"><div><h2>Notifications</h2><p>Activity requiring your attention</p></div></div><ul class="nr-list"><li class="nr-list-item"><div><strong>Story submitted for review</strong><p>Community Prevention Follow-up</p></div><span class="nr-tag">24m</span></li><li class="nr-list-item"><div><strong>Source verification requested</strong><p>National Health Strategy tracker</p></div><span class="nr-tag">1h</span></li><li class="nr-list-item"><div><strong>Briefing selection closes today</strong><p>Friday HealthTimes Weekly</p></div><span class="nr-tag">Today</span></li></ul></section>`;}
  function personalPerformancePanel(stories){return `<section class="nr-panel"><div class="nr-panel-head"><div><h2>Your work</h2><p>Current publishing record</p></div></div><ul class="nr-list"><li class="nr-list-item"><div><strong>Stories in workspace</strong><p>Owned or assigned</p></div><span class="nr-tag">${stories.length}</span></li><li class="nr-list-item"><div><strong>Published</strong><p>Current local publication dataset</p></div><span class="nr-tag">${stories.filter(s=>s.status==='Published').length}</span></li><li class="nr-list-item"><div><strong>Premium research</strong><p>Research-led work</p></div><span class="nr-tag">${stories.filter(s=>s.premium).length}</span></li></ul></section>`;}
  function publicationPulse(){const s=getStories();return `<section class="nr-panel"><div class="nr-panel-head"><div><h2>Publication pulse</h2><p>Structural newsroom metrics</p></div></div><ul class="nr-list"><li class="nr-list-item"><div><strong>Published</strong><p>Current story dataset</p></div><span class="nr-tag">${s.filter(x=>x.status==='Published').length}</span></li><li class="nr-list-item"><div><strong>In production</strong><p>Not yet published or archived</p></div><span class="nr-tag">${s.filter(x=>!['Published','Archived'].includes(x.status)).length}</span></li><li class="nr-list-item"><div><strong>Desks represented</strong><p>Active editorial coverage</p></div><span class="nr-tag">${new Set(s.map(x=>x.desk)).size}</span></li></ul></section>`;}
  function commercialPulse(){return `<section class="nr-panel"><div class="nr-panel-head"><div><h2>Commercial operations</h2><p>Inventory and membership readiness</p></div></div><ul class="nr-list"><li class="nr-list-item"><div><strong>HOSPAZ campaign</strong><p>Masthead · homepage · article</p></div>${status('Active')}</li><li class="nr-list-item"><div><strong>Premium proposition</strong><p>US$5 / month · research access</p></div><span class="nr-tag">Live</span></li><li class="nr-list-item"><div><strong>Commercial/editorial wall</strong><p>Story editing withheld from commercial role</p></div><span class="nr-tag">Enforced</span></li></ul></section>`;}
  function securityPulse(){return `<section class="nr-panel"><div class="nr-panel-head"><div><h2>Security</h2><p>Account governance</p></div><button data-module-jump="security">Open →</button></div><ul class="nr-list"><li class="nr-list-item"><div><strong>Role-based permissions</strong><p>Capability model active</p></div><span class="nr-tag">Active</span></li><li class="nr-list-item"><div><strong>MFA readiness</strong><p>Production integration required</p></div><span class="nr-tag">Prepared</span></li></ul></section>`;}
  function subscriberPulse(){return `<section class="nr-panel"><div class="nr-panel-head"><div><h2>Membership operations</h2><p>Premium product readiness</p></div><button data-module-jump="subscribers">Open →</button></div><ul class="nr-list"><li class="nr-list-item"><div><strong>Monthly membership</strong><p>US$5 proposition</p></div><span class="nr-tag">Configured</span></li><li class="nr-list-item"><div><strong>Premium preview</strong><p>Per-reader, per-story 30-second contract</p></div><span class="nr-tag">Active</span></li></ul></section>`;}
  function distributionQueue(){return `<section class="nr-panel"><div class="nr-panel-head"><div><h2>Distribution queue</h2><p>Scheduled editorial editions</p></div></div><ul class="nr-list"><li class="nr-list-item"><div><strong>Friday HealthTimes Weekly</strong><p>Email + WhatsApp · Friday 12:00</p></div>${status('Scheduled')}</li><li class="nr-list-item"><div><strong>Premium Intelligence</strong><p>Email · Friday 16:00</p></div>${status('Draft')}</li><li class="nr-list-item"><div><strong>Breaking health alerts</strong><p>Browser + WhatsApp selection</p></div><span class="nr-tag">Continuous</span></li></ul></section>`;}
  function audienceTopicPanel(){return `<section class="nr-panel"><div class="nr-panel-head"><div><h2>Reader interests</h2><p>Preference taxonomy</p></div></div><div class="nr-trend-list">${[['Global Health','76'],['HIV/AIDS','68'],['Health Policy','61'],['Research','54'],['Mental Health','47']].map((x,i)=>`<div class="nr-trend-row"><span class="nr-rank">0${i+1}</span><div><strong>${x[0]}</strong><div class="nr-progress"><span style="width:${x[1]}%"></span></div></div><span>${x[1]} index</span></div>`).join('')}</div></section>`;}
  function trendingPanel(){return `<section class="nr-panel"><div class="nr-panel-head"><div><h2>Trending topics</h2><p>Editorial attention signals</p></div><button data-module-jump="trending">Details →</button></div><div class="nr-trend-list">${[['Mpox','41'],['Malaria vaccines','32'],['Health financing','18'],['HIV prevention','12']].map((x,i)=>`<div class="nr-trend-row"><span class="nr-rank">0${i+1}</span><strong>${x[0]}</strong><span>↑ ${x[1]}%</span></div>`).join('')}</div></section>`;}
  function deskActivity(){const s=getStories();return `<div class="nr-trend-list">${[...new Set(s.map(x=>x.desk))].map((d,i)=>{const n=s.filter(x=>x.desk===d).length;return `<div class="nr-trend-row"><span class="nr-rank">${String(i+1).padStart(2,'0')}</span><div><strong>${esc(d)}</strong><div class="nr-progress"><span style="width:${Math.min(100,n*22)}%"></span></div></div><span>${n} stories</span></div>`}).join('')}</div>`;}

  function storyTable(list){return `<div class="nr-table-wrap"><table class="nr-table"><thead><tr><th>Story</th><th>Desk</th><th>Owner</th><th>Status</th><th>Deadline</th><th>Access</th><th>Actions</th></tr></thead><tbody>${list.map(s=>`<tr><td class="nr-title-cell"><strong>${esc(s.title)}</strong><span>${esc(s.section)} · Updated ${esc(s.updated)}</span></td><td>${esc(s.desk)}</td><td>${esc(staffRecord(s.owner)?.name||s.author)}</td><td>${status(s.status)}</td><td>${s.deadline?esc(new Date(s.deadline).toLocaleString()):'—'}</td><td><span class="nr-tag">${s.premium?'Premium':'Public'}</span></td><td><div class="nr-table-actions">${canEditStory(s)?`<button data-open-story="${esc(s.id)}">Open</button>`:''}${has(CAP.STORY_PUBLISH)&&['Ready','Scheduled'].includes(s.status)?`<button data-transition-story="${esc(s.id)}" data-next="Published">Publish</button>`:''}</div></td></tr>`).join('')}</tbody></table></div>`;}
  function renderStories(){const list=getStories();return `${head('Stories','Search and manage the complete editorial workflow.',has(CAP.STORY_CREATE)?button('＋ New story','data-quick-create','nr-primary'):'')}<section class="nr-panel"><div class="nr-filterbar"><input data-story-search placeholder="Search stories…"><select data-story-status><option value="">All statuses</option>${WORKFLOW.map(x=>`<option>${esc(x)}</option>`).join('')}</select><select data-story-desk><option value="">All desks</option>${DESKS.map(x=>`<option>${esc(x)}</option>`).join('')}</select></div><div data-story-table>${storyTable(list)}</div></section>`;}
  function renderMyStories(){const u=currentUser(),list=getStories().filter(s=>s.owner===u.username);return `${head('My stories','Everything you own or are actively reporting.',has(CAP.STORY_CREATE)?button('＋ New story','data-quick-create','nr-primary'):'')}<section class="nr-panel">${storyTable(list)}</section>`;}
  function renderSaved(){return `${head('Saved','Pinned working views and important newsroom references.')}${empty('No saved newsroom views yet')}`;}
  function renderMyAssignments(){const u=currentUser(),list=getAssignments().filter(a=>a.reporter===u.username);return `${head('My assignments','Accept, report and submit work assigned to you.')}<section class="nr-panel"><ul class="nr-list">${list.map(a=>assignmentList(a)).join('')||emptyRow('No assignments')}</ul></section>`;}
  function renderAssignments(){const list=getAssignments();return `${head('Assignments Desk','Create, monitor and rebalance reporting assignments.',has(CAP.ASSIGN_CREATE)?button('＋ Create assignment','data-open-assignment','nr-primary'):'')}<section class="nr-panel"><div class="nr-table-wrap"><table class="nr-table"><thead><tr><th>Assignment</th><th>Reporter</th><th>Desk</th><th>Deadline</th><th>Priority</th><th>Status</th><th>Action</th></tr></thead><tbody>${list.map(a=>{const overdue=new Date(a.deadline)<new Date()&&a.status!=='Complete';return `<tr><td class="nr-title-cell"><strong>${esc(a.title)}</strong><span>${esc(a.notes)}</span></td><td>${esc(staffRecord(a.reporter)?.name||a.reporter)}</td><td>${esc(a.desk)}</td><td>${esc(new Date(a.deadline).toLocaleString())}</td><td><span class="nr-tag">${esc(a.priority)}</span></td><td>${status(overdue?'Overdue':a.status)}</td><td>${a.reporter===currentUser().username?button('Advance',`data-assignment-progress="${esc(a.id)}"`):''}</td></tr>`}).join('')}</tbody></table></div></section>`;}
  function renderReview(){const list=getStories().filter(s=>['Submitted','Fact check','Health / Science review','Copy edit','Editor review','Ready'].includes(s.status));return `${head('Review Queue','Submitted work, evidence checks and publication decisions.')}<section class="nr-panel">${list.map(reviewCard).join('')||empty('Review queue is clear')}</section>`;}
  function renderCalendar(){const events=[['09 Sep · 09:00','Editorial conference','Meeting','Global + Africa desks'],['09 Sep · 12:00','STI analysis editor deadline','Deadline','Community Prevention Follow-up'],['09 Sep · 15:30','WhatsApp briefing lock','Briefing','Audience Desk'],['10 Sep · 12:00','National Health Strategy fact check','Deadline','Policy desk'],['10 Sep · 16:00','World Suicide Prevention Day coverage','Health date','Mental Health desk'],['11 Sep · 12:00','Friday HealthTimes Weekly','Briefing','Email + WhatsApp']];return `${head('Editorial Calendar','Deadlines, interviews, publication, briefings and global-health dates.',has(CAP.ASSIGN_CREATE)?button('＋ Assignment','data-open-assignment','nr-primary'):'')}<section class="nr-panel"><div class="nr-calendar">${events.map(e=>`<div class="nr-calendar-time">${esc(e[0])}</div><div class="nr-calendar-event" data-kind="${esc(e[2])}"><strong>${esc(e[1])}</strong><span>${esc(e[2])} · ${esc(e[3])}</span></div>`).join('')}</div></section>`;}
  function renderBreaking(){return `${head('Breaking News','Fast-moving coverage requiring clear ownership and update discipline.')}<section class="nr-panel">${getStories().filter(s=>s.distribution?.breaking||s.section==='Breaking News').map(storyList).join('')||empty('No active breaking desk items')}</section>`;}
  function renderCorrections(){return `${head('Corrections','Published changes, corrections and accountability record.')}<section class="nr-panel">${getStories().filter(s=>['Updated / Corrected'].includes(s.status)).map(storyList).join('')||empty('No corrections are waiting')}</section>`;}
  function renderMedia(){return `${head('Media Library','Editorial images, documents, campaign assets and source media.',has(CAP.MEDIA)?button('＋ Add media','','nr-primary'):'')}<section class="nr-panel"><div class="nr-filterbar"><input placeholder="Search media…"><select><option>All types</option><option>Image</option><option>Video</option><option>Audio</option><option>Document</option></select></div><div class="nr-media-grid">${getMedia().map(m=>`<article class="nr-media-card"><span class="nr-tag">${esc(m.type)}</span><strong>${esc(m.filename)}</strong><span>${esc(m.caption)}</span><span>Credit: ${esc(m.credit)}</span><span>Used in: ${esc(m.usedIn)}</span><span>${esc(m.date)}</span></article>`).join('')}</div></section>`;}
  function personCard(s){return `<article class="nr-person-card"><span class="nr-avatar">${esc(initials(s.name))}</span><div><strong>${esc(s.name)}</strong><span>${esc(s.role)}</span><span>${esc(s.desk)} · ${esc(s.beat)}</span></div></article>`;}
  function renderAuthors(){return `${head('Authors','Staff identity, beats and public author authority.')}<section class="nr-panel"><div class="nr-staff-card-grid">${getStaff().filter(s=>!['Commercial Manager','Subscriber Manager'].includes(s.role)).map(personCard).join('')}</div></section>`;}
  function renderTopics(){const topics=['HIV/AIDS','Malaria','Outbreaks','Medicines','Health financing','Mental health','Maternal health','Research','Health systems','Innovation'];return `${head('Topics','Editorial subject taxonomy used for reporting, SEO and reader follows.')}<section class="nr-panel"><div class="nr-source-grid">${topics.map(t=>`<article class="nr-source-card"><strong>${esc(t)}</strong><span>${getStories().filter(s=>s.topic===t).length} mapped stories</span><span>Topic hub ready</span></article>`).join('')}</div></section>`;}
  function renderRegions(){return `${head('Countries & regions','Global health coverage with Africa as a primary editorial advantage.')}<section class="nr-panel"><div class="nr-source-grid">${REGIONS.map(r=>`<article class="nr-source-card"><strong>${esc(r)}</strong><span>${getStories().filter(s=>s.region===r).length} current stories</span><span>Desk taxonomy active</span></article>`).join('')}</div></section>`;}
  function renderSources(){return `${head('Research / Sources','Primary documents and evidence used across HealthTimes reporting.')}<section class="nr-panel"><div class="nr-source-grid">${[['Parliamentary Committee evidence','Institutional source','NatPharm investigation'],['National AIDS Council briefing','Institutional source','STI coverage'],['Africa CDC surveillance','Public-health source','Outbreak Watch'],['WHO outbreak notices','Global source','Africa outbreak coverage'],['National Health Strategy','Policy document','Implementation tracker'],['Peer-reviewed literature','Research source','Premium analysis']].map(x=>`<article class="nr-source-card"><strong>${x[0]}</strong><span>${x[1]}</span><span>Used in: ${x[2]}</span></article>`).join('')}</div></section>`;}
  function renderArchive(){return `${head('Archive','Published, corrected and archived editorial inventory.')}<section class="nr-panel">${storyTable(getStories().filter(s=>['Published','Updated / Corrected','Archived'].includes(s.status)))}</section>`;}

  function renderHomepage(){return `${head('Homepage','Editorial homepage curation and distribution readiness.')}<section class="nr-panel"><div class="nr-panel-head"><div><h2>Current homepage candidates</h2><p>Published stories selected for front-page treatment</p></div></div><ul class="nr-list">${getStories().filter(s=>s.distribution?.homepage).map(storyList).join('')}</ul></section>`;}
  function renderNewsletter(){return `${head('Newsletters','Build recurring editorial editions from approved HealthTimes reporting.')}<div class="nr-grid nr-grid-2"><section class="nr-panel"><div class="nr-panel-head"><div><h2>HealthTimes Weekly</h2><p>Friday · Email + WhatsApp</p></div>${status('Scheduled')}</div><ul class="nr-list"><li class="nr-list-item"><div><strong>Selected stories</strong><p>5 public + 1 Premium research item</p></div><span class="nr-tag">6</span></li><li class="nr-list-item"><div><strong>Editorial lock</strong><p>Friday 10:00</p></div><span class="nr-tag">Pending</span></li></ul></section><section class="nr-panel"><div class="nr-panel-head"><div><h2>Premium Intelligence</h2><p>Member research briefing</p></div>${status('Draft')}</div><ul class="nr-list"><li class="nr-list-item"><div><strong>Research notes</strong><p>Policy + financing + evidence</p></div><span class="nr-tag">3</span></li></ul></section></div>`;}
  function renderWhatsApp(){return `${head('WhatsApp Desk','Article distribution, reader comments and recurring briefing operations.')}<section class="nr-panel"><ul class="nr-list"><li class="nr-list-item"><div><strong>Weekly health briefing</strong><p>Friday 12:00 · publication channel</p></div>${status('Scheduled')}</li><li class="nr-list-item"><div><strong>Reader comments</strong><p>Route corrections, tips and feedback to the appropriate desk</p></div><span class="nr-tag">Open</span></li><li class="nr-list-item"><div><strong>Breaking alerts</strong><p>Requires editor-approved story selection</p></div><span class="nr-tag">Ready</span></li></ul></section>`;}
  function renderSocial(){return `${head('Social Desk','Coordinate HealthTimes reporting across social channels without changing editorial copy.')}<section class="nr-panel"><div class="nr-source-grid">${['WhatsApp','Facebook','X','LinkedIn','Instagram','YouTube'].map(x=>`<article class="nr-source-card"><strong>${x}</strong><span>Distribution channel</span><span>Editorial approval required for breaking alerts</span></article>`).join('')}</div></section>`;}
  function renderPush(){return `${head('Push alerts','High-priority browser/app notifications tied to approved reporting.')}<section class="nr-panel">${empty('No push alert is currently queued')}</section>`;}

  function renderAnalytics(){const s=getStories();return `${head('Analytics','Structural publication metrics plus the presentation layer for production audience analytics.')}<div class="nr-note">Story inventory and workflow counts are derived from the local editorial dataset. Reach and engagement panels illustrate the production analytics surface and require a real event pipeline before launch.</div><div class="nr-grid nr-grid-4">${stat('Stories',s.length,'Current editorial inventory','teal')}${stat('Published',s.filter(x=>x.status==='Published').length,'Current published records','green')}${stat('In review',s.filter(x=>['Submitted','Fact check','Health / Science review','Copy edit','Editor review'].includes(x.status)).length,'Review workflow','amber')}${stat('Desks',new Set(s.map(x=>x.desk)).size,'Coverage groups represented','blue')}</div><div class="nr-dashboard-columns"><section class="nr-panel"><div class="nr-panel-head"><div><h2>Desk mix</h2><p>Current editorial inventory</p></div></div>${deskActivity()}</section><section class="nr-panel"><div class="nr-panel-head"><div><h2>Production analytics integration</h2><p>Planned live metrics</p></div></div><ul class="nr-list"><li class="nr-list-item"><div><strong>Engaged reading time</strong><p>Requires event analytics</p></div><span class="nr-tag">Connect</span></li><li class="nr-list-item"><div><strong>Country & referral</strong><p>Global audience acquisition</p></div><span class="nr-tag">Connect</span></li><li class="nr-list-item"><div><strong>Premium conversion</strong><p>Requires billing + entitlement analytics</p></div><span class="nr-tag">Connect</span></li></ul></section></div>`;}
  function renderTrending(){return `${head('Trending','Topic and story signals for editorial prioritisation.')}${trendingPanel()}<section class="nr-panel nr-section-space"><div class="nr-panel-head"><div><h2>Story intelligence</h2><p>Presentation model for live production metrics</p></div></div><div class="nr-table-wrap"><table class="nr-table"><thead><tr><th>Story</th><th>Reads</th><th>Engaged time</th><th>Completion</th><th>Shares</th><th>Saves</th><th>Premium joins</th></tr></thead><tbody><tr><td class="nr-title-cell"><strong>Parliament Probes NatPharm...</strong></td><td>Live integration</td><td>Live integration</td><td>Live integration</td><td>Live integration</td><td>Live integration</td><td>Live integration</td></tr></tbody></table></div></section>`;}
  function renderSEO(){return `${head('SEO Desk','Search presentation, metadata completeness and topic authority.')}<section class="nr-panel"><div class="nr-table-wrap"><table class="nr-table"><thead><tr><th>Story</th><th>SEO title</th><th>Meta</th><th>Slug</th><th>Region</th></tr></thead><tbody>${getStories().map(s=>`<tr><td class="nr-title-cell"><strong>${esc(s.title)}</strong></td><td>${s.seoTitle?'Ready':'Missing'}</td><td>${s.metaDescription?'Ready':'Missing'}</td><td>${esc(s.slug||'—')}</td><td>${esc(s.region)}</td></tr>`).join('')}</tbody></table></div></section>`;}
  function renderCitations(){return `${head('Citations & Impact','Build HealthTimes into a globally citable health-research publication.')}<div class="nr-note">External citation counts require backlink, academic and institutional integrations. This workspace defines the operating model without presenting unverified live counts.</div><div class="nr-grid nr-grid-4">${stat('Citation-ready research',getStories().filter(s=>s.premium&&s.sources).length,'Premium stories with sources','teal')}${stat('Source-backed stories',getStories().filter(s=>s.sources).length,'Stories with evidence records','blue')}${stat('External citations','Connect','Backlink / scholarly integration','amber')}${stat('Institutional mentions','Connect','Government / NGO monitoring','green')}</div><section class="nr-panel nr-section-space"><div class="nr-panel-head"><div><h2>Research impact queue</h2><p>Stories positioned for citation tracking</p></div></div><ul class="nr-list">${getStories().filter(s=>s.premium).map(s=>`<li class="nr-list-item"><div><strong>${esc(s.title)}</strong><p>${esc(s.sources||'Sources pending')}</p></div><span class="nr-tag">Track citations</span></li>`).join('')}</ul></section>`;}
  function renderAI(){return `${head('AI Desk','Editorial assistance for evidence, source discovery and newsroom context — never automatic publishing.')}<div class="nr-grid nr-grid-3">${[['Evidence gaps','Check a draft for factual claims without attached sources.'],['Archive context','Find related HealthTimes reporting and internal links.'],['Source summary','Summarise a document for editorial review.'],['Interview questions','Generate questions from the reporting brief and known evidence.'],['SEO alternatives','Suggest precise headlines and descriptions without changing copy automatically.'],['Citation check','Flag missing references and evidence metadata.']].map(x=>`<section class="nr-panel"><div class="nr-panel-head"><div><h2>${x[0]}</h2><p>${x[1]}</p></div></div><div style="padding:14px">${button('Open tool','','nr-secondary')}</div></section>`).join('')}</div>`;}

  function renderPremium(){const list=getStories().filter(s=>s.premium||has(CAP.PREMIUM_ASSIGN));return `${head('Premium','Research access, publishing stage and membership value.',has(CAP.PREMIUM_MANAGE)?button('View membership operations','data-module-jump="subscribers"','nr-secondary'):'')}<section class="nr-panel" data-v21-premium-admin><div class="nr-panel-head"><div><h2>Premium publishing controls</h2><p>Authorised changes update the public story access override.</p></div></div><div class="nr-table-wrap"><table class="nr-table"><thead><tr><th>Story</th><th>Status</th><th>Sources</th><th>Access</th><th>Action</th></tr></thead><tbody>${list.map(s=>`<tr><td class="nr-title-cell"><strong>${esc(s.title)}</strong><span>${esc(s.desk)}</span></td><td>${status(s.status)}</td><td>${s.sources?'Recorded':'Needs sources'}</td><td><span class="nr-tag">${s.premium?'Premium':'Public'}</span></td><td>${has(CAP.PREMIUM_ASSIGN)?`<button class="nr-secondary" data-v21-premium-toggle="${esc(s.id)}">${s.premium?'Make public':'Make Premium'}</button>`:'—'}</td></tr>`).join('')}</tbody></table></div></section>`;}
  function renderSubscribers(){return `${head('Subscribers','Membership service, reader accounts and Premium support operations.')}<div class="nr-grid nr-grid-3">${stat('Membership price','US$5','Monthly Premium proposition','teal')}${stat('Preview contract','30 sec','Per-reader, per-story access','amber')}${stat('Billing','Connect','Production payment provider required','blue')}</div><section class="nr-panel nr-section-space"><div class="nr-panel-head"><div><h2>Subscriber operations</h2><p>Production identity and billing service integration points</p></div></div><ul class="nr-list"><li class="nr-list-item"><div><strong>Reader identity</strong><p>Account, saved stories and preferences</p></div><span class="nr-tag">Frontend ready</span></li><li class="nr-list-item"><div><strong>Entitlements</strong><p>Server-side membership required for production</p></div><span class="nr-tag">Integrate</span></li><li class="nr-list-item"><div><strong>Support status</strong><p>Subscriber manager workflow</p></div><span class="nr-tag">Prepared</span></li></ul></section>`;}
  function campaignTable(list){return `<div class="nr-table-wrap"><table class="nr-table"><thead><tr><th>Campaign</th><th>Advertiser</th><th>Placement</th><th>Dates</th><th>Status</th><th>Review</th></tr></thead><tbody>${list.map(c=>`<tr><td class="nr-title-cell"><strong>${esc(c.name)}</strong><span>${esc(c.label||'Advertisement')}</span></td><td>${esc(c.advertiser)}</td><td>${esc((c.placement||[]).join(' · '))}</td><td>${esc(c.start)} → ${esc(c.end)}</td><td>${status(c.status)}</td><td><span class="nr-tag">${esc(c.review)}</span></td></tr>`).join('')}</tbody></table></div>`;}
  function renderAdvertising(){return `${head('Advertising','Paid inventory, campaign governance and commercial review.',has(CAP.ADS_CREATE)?button('＋ New campaign','','nr-primary'):'')}<div class="nr-note">Commercial staff can manage advertising and membership operations but cannot edit newsroom stories.</div><section class="nr-panel"><div class="nr-panel-head"><div><h2>Campaign inventory</h2><p>Masthead, in-feed, article and briefing placements</p></div></div>${campaignTable(read(KEYS.campaigns,initialCampaigns))}</section><section class="nr-panel nr-section-space"><div class="nr-panel-head"><div><h2>HOSPAZ creative</h2><p>Current paid campaign retained from the source publication</p></div></div><div style="padding:14px"><img src="${HOSPAZ}" alt="HOSPAZ Annual General Meeting advertisement" style="display:block;width:100%;height:auto;object-fit:contain;border-radius:8px"></div></section>`;}

  function renderStaff(){const list=getStaff();return `${head('Staff & Access','Invite, assign, suspend and revoke Newsroom access.',has(CAP.STAFF_INVITE)?button('＋ Invite staff','data-open-invite','nr-primary'):'')}<section class="nr-panel"><div class="nr-table-wrap"><table class="nr-table"><thead><tr><th>Staff</th><th>Role</th><th>Desk</th><th>Status</th><th>Last login</th><th>Security</th><th>Actions</th></tr></thead><tbody>${list.map(s=>`<tr><td class="nr-title-cell"><strong>${esc(s.name)}</strong><span>${esc(s.email)} · ${esc(s.beat)}</span></td><td>${esc(s.role)}</td><td>${esc(s.desk)}</td><td>${status(s.status)}</td><td>${esc(s.lastLogin||'Never')}</td><td><span class="nr-tag">MFA ${esc(s.mfa||'Pending')}</span></td><td><div class="nr-table-actions">${has(CAP.STAFF_ROLE)&&s.username!==currentUser().username?`<button data-staff-role="${esc(s.username)}">Change role</button>`:''}${has(CAP.STAFF_REVOKE)&&s.username!==currentUser().username?`<button data-staff-sessions="${esc(s.username)}">Revoke sessions</button><button data-staff-revoke="${esc(s.username)}">Revoke access</button>`:''}</div></td></tr>`).join('')}</tbody></table></div></section>`;}
  function renderRoles(){return `${head('Roles & Permissions','Capabilities define authority; roles group capabilities for newsroom work.')}<section class="nr-panel"><div class="nr-capability-grid">${Object.entries(ROLE_CAPS).map(([role,cs])=>`<article class="nr-role-card"><h3>${esc(role)}</h3><p>${cs.length} configured capabilities</p><ul>${cs.slice(0,8).map(c=>`<li>${esc(c)}</li>`).join('')}${cs.length>8?`<li>+ ${cs.length-8} more</li>`:''}</ul></article>`).join('')}</div></section>`;}
  function renderAudit(){const list=read(KEYS.audit,[]);return `${head('Audit Log','Operational history for sign-in, publishing, Premium and access changes.')}<section class="nr-panel"><ul class="nr-audit-list">${list.map(x=>`<li><time>${esc(new Date(x.at).toLocaleString())}</time><span>${esc(x.user)} · ${esc(x.role)}</span><strong>${esc(x.action)}</strong></li>`).join('')||'<li><span>No audit entries yet.</span></li>'}</ul></section>`;}
  function renderSettings(){return `${head('Settings','Newsroom preferences and publication defaults.')}<div class="nr-grid nr-grid-2"><section class="nr-panel"><div class="nr-panel-head"><div><h2>My profile</h2><p>Current staff identity</p></div></div><ul class="nr-list"><li class="nr-list-item"><div><strong>${esc(currentUser().name)}</strong><p>${esc(currentUser().email)}</p></div><span class="nr-tag">${esc(currentUser().role)}</span></li><li class="nr-list-item"><div><strong>Primary desk</strong><p>${esc(currentUser().desk)}</p></div><span class="nr-tag">${esc(currentUser().beat)}</span></li></ul></section><section class="nr-panel"><div class="nr-panel-head"><div><h2>Editorial defaults</h2><p>Production settings require server-side persistence</p></div></div><ul class="nr-list"><li class="nr-list-item"><div><strong>Default timezone</strong><p>Africa/Harare</p></div><span class="nr-tag">UTC+2</span></li><li class="nr-list-item"><div><strong>Autosave</strong><p>Story drafts save while editing</p></div><span class="nr-tag">On</span></li></ul></section></div>`;}
  function renderIntegrations(){return `${head('Integrations','Production connections for publishing, identity, analytics and distribution.')}<section class="nr-panel"><div class="nr-source-grid">${[['CMS / Database','Replace local story persistence'],['Identity + MFA','Replace local staff credentials'],['Analytics','Reads, engagement, geography and referrals'],['Email','Newsletter delivery'],['WhatsApp Business','Briefings and reader messaging'],['Payments','Premium billing and entitlement'],['Citation monitoring','Backlinks and academic mentions'],['Ad events','Campaign impressions and clicks']].map(x=>`<article class="nr-source-card"><strong>${x[0]}</strong><span>${x[1]}</span><span>Production integration</span></article>`).join('')}</div></section>`;}
  function renderSecurity(){const u=currentUser(),all=read(KEYS.sessions,{}),sessions=all[u.username]||[{id:'current',device:'Current browser',location:'Current session',lastActive:'Now',current:true}];return `${head('Security','Sessions, access state and account security.',has(CAP.SECURITY)?button('View audit','data-module-jump="audit"','nr-secondary'):'')}<div class="nr-grid nr-grid-2"><section class="nr-panel"><div class="nr-panel-head"><div><h2>Sessions</h2><p>Signed-in devices for this staff account</p></div></div>${sessions.map(s=>`<div class="nr-security-session"><div><strong>${esc(s.device)}</strong><p>${esc(s.location)} · ${esc(s.lastActive)}</p></div>${s.current?'<span class="nr-tag">Current</span>':button('Revoke',`data-revoke-session="${esc(s.id)}"`)}</div>`).join('')}</section><section class="nr-panel"><div class="nr-panel-head"><div><h2>Account security</h2><p>Identity controls</p></div></div><ul class="nr-list"><li class="nr-list-item"><div><strong>MFA</strong><p>Production managed identity requirement</p></div><span class="nr-tag">${esc(u.mfa||'Pending')}</span></li><li class="nr-list-item"><div><strong>Password status</strong><p>${u.passwordChange?'Change required':'No forced change'}</p></div><span class="nr-tag">Protected</span></li><li class="nr-list-item"><div><strong>Role</strong><p>${esc(u.role)}</p></div><span class="nr-tag">RBAC</span></li></ul></section></div>`;}

  function openStory(id=null){const u=currentUser();if(id){const s=getStories().find(x=>x.id===id);if(!s||!canEditStory(s)){toast('You do not have permission to edit this story.');return;}editingStoryId=id;}else{if(!has(CAP.STORY_CREATE)){toast('Your role cannot create stories.');return;}editingStoryId=`s-${Date.now().toString(36)}`;const s={id:editingStoryId,title:'',standfirst:'',body:'',sources:'',notes:'',section:'Health News',desk:u.desk||'Global Health',country:u.country||'',region:u.region||'Global',topic:'',premium:false,owner:u.username,author:u.name,editor:isEditor()?u.username:'editor',factChecker:'',status:'Draft',deadline:'',schedule:'',updated:stamp(),seoTitle:'',metaDescription:'',slug:'',adSetting:'Standard',distribution:{homepage:false,breaking:false,newsletter:false,whatsapp:false,push:false},versions:[]};const list=getStories();list.unshift(s);setStories(list);audit(`${u.name} created a new story draft`);}
    populateEditor();$('[data-story-modal]').hidden=false;document.body.style.overflow='hidden';}
  function closeStory(){flushAutosave();$('[data-story-modal]').hidden=true;document.body.style.overflow='';editingStoryId=null;}
  function staffOptions(selected='',roles=null){return getStaff().filter(s=>s.status==='Active'&&(!roles||roles.includes(s.role))).map(s=>`<option value="${esc(s.username)}" ${s.username===selected?'selected':''}>${esc(s.name)} · ${esc(s.role)}</option>`).join('');}
  function populateEditor(){const s=getStories().find(x=>x.id===editingStoryId);if(!s)return;const form=$('[data-story-form]'), shadow=$('[data-story-shadow]');form.elements.id.value=s.id;form.elements.title.value=s.title||'';form.elements.standfirst.value=s.standfirst||'';form.elements.body.value=s.body||'';form.elements.sources.value=s.sources||'';form.elements.notes.value=s.notes||'';const fields={status:s.status,deadline:s.deadline||'',owner:s.owner,editor:s.editor||'',factChecker:s.factChecker||'',desk:s.desk||'',section:s.section||'',country:s.country||'',region:s.region||'Global',premium:String(!!s.premium),seoTitle:s.seoTitle||'',metaDescription:s.metaDescription||'',slug:s.slug||'',adSetting:s.adSetting||'Standard',schedule:s.schedule||''};const owner=$('[name="owner"][form="story-shadow"]'), editor=$('[name="editor"][form="story-shadow"]'), checker=$('[name="factChecker"][form="story-shadow"]'), desk=$('[name="desk"][form="story-shadow"]'), region=$('[name="region"][form="story-shadow"]');owner.innerHTML=staffOptions(s.owner,['Reporter / Journalist','Editor-in-Chief','Managing Editor','Section Editor','News Editor']);editor.innerHTML=`<option value="">Unassigned</option>${staffOptions(s.editor,['Publisher / Owner','Editor-in-Chief','Managing Editor','Section Editor','News Editor'])}`;checker.innerHTML=`<option value="">Unassigned</option>${staffOptions(s.factChecker,['Fact Checker','Health / Science Editor','Editor-in-Chief'])}`;desk.innerHTML=DESKS.map(x=>`<option ${x===s.desk?'selected':''}>${x}</option>`).join('');region.innerHTML=REGIONS.map(x=>`<option ${x===s.region?'selected':''}>${x}</option>`).join('');Object.entries(fields).forEach(([k,v])=>{const el=$(`[name="${k}"][form="story-shadow"]`);if(el)el.value=v;});['Homepage','Breaking','Newsletter','WhatsApp','Push'].forEach(k=>{const el=$(`[name="dist${k}"][form="story-shadow"]`);if(el)el.checked=!!s.distribution?.[k.toLowerCase()];});$('[data-story-modal-title]').textContent=s.title||'Untitled story';$('[data-editor-state]').textContent=s.status;$('[data-save-state]').textContent='Saved';renderVersions(s);renderComments(s);configureEditorAction(s);protectInspector(s);}
  function protectInspector(s){const reporterOnly=!has(CAP.STORY_EDIT_ALL);['status','owner','editor','factChecker'].forEach(n=>{const el=$(`[name="${n}"][form="story-shadow"]`);if(el)el.disabled=reporterOnly;});const premium=$('[name="premium"][form="story-shadow"]');if(premium)premium.disabled=!has(CAP.PREMIUM_ASSIGN);}
  function formStory(){const old=getStories().find(x=>x.id===editingStoryId);if(!old)return null;const f=$('[data-story-form]'), d=new FormData($('[data-story-shadow]'));const story={...old,title:f.elements.title.value.trim(),standfirst:f.elements.standfirst.value.trim(),body:f.elements.body.value,sources:f.elements.sources.value,notes:f.elements.notes.value,status:String(d.get('status')||old.status),deadline:String(d.get('deadline')||''),owner:String(d.get('owner')||old.owner),editor:String(d.get('editor')||''),factChecker:String(d.get('factChecker')||''),desk:String(d.get('desk')||old.desk),section:String(d.get('section')||old.section),country:String(d.get('country')||old.country),region:String(d.get('region')||old.region),premium:String(d.get('premium'))==='true',seoTitle:String(d.get('seoTitle')||''),metaDescription:String(d.get('metaDescription')||''),slug:String(d.get('slug')||slugify(f.elements.title.value)),adSetting:String(d.get('adSetting')||'Standard'),schedule:String(d.get('schedule')||''),updated:stamp(),author:staffRecord(String(d.get('owner')||old.owner))?.name||old.author,distribution:{homepage:!!d.get('distHomepage'),breaking:!!d.get('distBreaking'),newsletter:!!d.get('distNewsletter'),whatsapp:!!d.get('distWhatsApp'),push:!!d.get('distPush')}};if(!has(CAP.STORY_EDIT_ALL)){story.status=old.status;story.owner=old.owner;story.editor=old.editor;story.factChecker=old.factChecker;}if(!has(CAP.PREMIUM_ASSIGN))story.premium=old.premium;return story;}
  function saveStory(manual=false){if(!editingStoryId)return;const story=formStory();if(!story)return;const list=getStories(),idx=list.findIndex(x=>x.id===editingStoryId),old=list[idx];const meaningful=JSON.stringify([old.title,old.standfirst,old.body,old.sources,old.status,old.premium])!==JSON.stringify([story.title,story.standfirst,story.body,story.sources,story.status,story.premium]);if(manual||meaningful){story.versions=[...(old.versions||[])];story.versions.unshift({at:iso(),by:currentUser().name,label:manual?'Manual save':'Autosave'});story.versions=story.versions.slice(0,10);}list[idx]=story;setStories(list);syncPremium(story);$('[data-save-state]').textContent='Saved';$('[data-story-modal-title]').textContent=story.title||'Untitled story';$('[data-editor-state]').textContent=story.status;renderVersions(story);configureEditorAction(story);if(manual){audit(`${currentUser().name} saved “${story.title||'Untitled story'}”`);toast('Story saved');}}
  function scheduleAutosave(){if(!editingStoryId)return;$('[data-save-state]').textContent='Saving…';clearTimeout(autosaveTimer);autosaveTimer=setTimeout(()=>saveStory(false),650);}
  function flushAutosave(){if(autosaveTimer){clearTimeout(autosaveTimer);autosaveTimer=null;saveStory(false);}}
  function renderVersions(s){$('[data-version-list]').innerHTML=(s.versions||[]).slice(0,6).map(v=>`<div class="nr-version"><strong>${esc(v.label)}</strong><span>${esc(v.by)} · ${esc(new Date(v.at).toLocaleString())}</span></div>`).join('')||'<div class="nr-version"><span>No saved versions yet</span></div>';}
  function renderComments(s){const map=read(KEYS.comments,{}),items=map[s.id]||[];$('[data-editor-comments]').innerHTML=items.map(c=>`<article class="nr-comment"><strong>${esc(c.user)}</strong><time>${esc(new Date(c.at).toLocaleString())}</time><p>${esc(c.text)}</p>${c.resolved?'<span class="nr-tag">Resolved</span>':''}</article>`).join('')||'<div class="nr-empty"><p>No internal comments yet.</p></div>';}
  function configureEditorAction(s){const btn=$('[data-editor-primary]');if(has(CAP.STORY_PUBLISH)&&['Ready','Scheduled','Editor review'].includes(s.status)){btn.textContent='Publish';btn.dataset.action='publish';return;}if(has(CAP.STORY_EDIT_ALL)&&s.status==='Submitted'){btn.textContent='Send to fact check';btn.dataset.action='fact';return;}if(has(CAP.STORY_EDIT_ALL)&&['Fact check','Health / Science review','Copy edit'].includes(s.status)){btn.textContent='Advance review';btn.dataset.action='advance';return;}btn.textContent='Submit for review';btn.dataset.action='submit';btn.disabled=!has(CAP.STORY_SUBMIT);}
  function primaryEditorAction(){flushAutosave();const s=getStories().find(x=>x.id===editingStoryId);if(!s)return;const action=$('[data-editor-primary]').dataset.action;if(action==='publish'){transitionStory(s.id,'Published');return;}if(action==='fact'){transitionStory(s.id,'Fact check');return;}if(action==='advance'){const next={'Fact check':'Health / Science review','Health / Science review':'Copy edit','Copy edit':'Editor review'}[s.status]||'Editor review';transitionStory(s.id,next);return;}if(has(CAP.STORY_SUBMIT)){transitionStory(s.id,'Submitted');}}
  function transitionStory(id,next){const list=getStories(),s=list.find(x=>x.id===id);if(!s)return;if(next==='Published'&&!has(CAP.STORY_PUBLISH)){toast('Publishing authority is required.');return;}if(next==='Fact check'&&!has(CAP.STORY_EDIT_ALL)){toast('Editorial review authority is required.');return;}if(next==='Submitted'&&!(has(CAP.STORY_SUBMIT)&&canEditStory(s))){toast('You cannot submit this story.');return;}s.status=next;s.updated=stamp();s.versions=[{at:iso(),by:currentUser().name,label:`Moved to ${next}`},...(s.versions||[])].slice(0,10);setStories(list);syncPremium(s);audit(`${currentUser().name} moved “${s.title}” to ${next}`);if(editingStoryId===id)populateEditor();else showModule(active);toast(`Story moved to ${next}`);}

  function assignmentProgress(id){const list=getAssignments(),a=list.find(x=>x.id===id);if(!a||a.reporter!==currentUser().username)return;const seq=['Assigned','Accepted','Reporting','Drafting','Submitted','Complete'];const i=Math.max(0,seq.indexOf(a.status));a.status=seq[Math.min(i+1,seq.length-1)];setAssignments(list);audit(`${currentUser().name} moved assignment “${a.title}” to ${a.status}`);showModule(active);toast(`Assignment: ${a.status}`);}
  function openAssignment(){if(!has(CAP.ASSIGN_CREATE))return;const f=$('[data-assignment-form]');f.reset();f.elements.reporter.innerHTML=staffOptions('', ['Reporter / Journalist']);f.elements.editor.innerHTML=staffOptions(currentUser().username,['Publisher / Owner','Editor-in-Chief','Managing Editor','Section Editor','News Editor']);f.elements.desk.innerHTML=DESKS.filter(x=>!['Commercial'].includes(x)).map(x=>`<option>${x}</option>`).join('');$('[data-assignment-modal]').hidden=false;}
  function saveAssignment(form){const d=new FormData(form),a={id:`a-${Date.now().toString(36)}`,title:String(d.get('title')),reporter:String(d.get('reporter')),desk:String(d.get('desk')),deadline:String(d.get('deadline')),priority:String(d.get('priority')),editor:String(d.get('editor')),status:'Assigned',notes:String(d.get('notes')||'')};const list=getAssignments();list.unshift(a);setAssignments(list);audit(`${currentUser().name} assigned “${a.title}” to ${staffRecord(a.reporter)?.name||a.reporter}`);$('[data-assignment-modal]').hidden=true;showModule('assignments');toast('Assignment created');}

  function openInvite(){if(!has(CAP.STAFF_INVITE))return;const f=$('[data-invite-form]');f.reset();f.elements.role.innerHTML=Object.keys(ROLE_CAPS).map(x=>`<option>${esc(x)}</option>`).join('');f.elements.desk.innerHTML=DESKS.map(x=>`<option>${esc(x)}</option>`).join('');f.elements.editor.innerHTML=`<option value="">None</option>${staffOptions('', ['Publisher / Owner','Editor-in-Chief','Managing Editor','Section Editor','News Editor'])}`;$('[data-invite-modal]').hidden=false;}
  function saveInvite(form){const d=new FormData(form),name=String(d.get('name')),email=String(d.get('email')),username=`invited-${Date.now().toString(36)}`;const list=getStaff();list.push({username,name,email,role:String(d.get('role')),desk:String(d.get('desk')),beat:'To be assigned',country:String(d.get('country')||''),region:'Global',status:'Invited',editor:String(d.get('editor')||''),lastLogin:'Never',passwordChange:true,mfa:'Pending'});setStaff(list);audit(`${currentUser().name} invited ${name} as ${String(d.get('role'))}`);$('[data-invite-modal]').hidden=true;showModule('staff');toast('Staff invitation created');}
  function changeStaffRole(username){if(!has(CAP.STAFF_ROLE))return;const s=staffRecord(username);if(!s)return;const roles=Object.keys(ROLE_CAPS),i=roles.indexOf(s.role);s.role=roles[(i+1)%roles.length];setStaff(getStaff().map(x=>x.username===username?s:x));audit(`${currentUser().name} changed ${s.name} role to ${s.role}`);showModule('staff');toast('Role updated');}
  function confirm(title,copy,fn){pendingConfirm=fn;$('[data-confirm-title]').textContent=title;$('[data-confirm-copy]').textContent=copy;$('[data-confirm-modal]').hidden=false;}
  function revokeAccess(username){if(!has(CAP.STAFF_REVOKE))return;const s=staffRecord(username);if(!s)return;confirm('Revoke Newsroom access?',`${s.name} will no longer be able to sign in to HealthTimes Newsroom.`,()=>{s.status='Revoked';setStaff(getStaff().map(x=>x.username===username?s:x));const sessions=read(KEYS.sessions,{});delete sessions[username];write(KEYS.sessions,sessions);audit(`${currentUser().name} revoked Newsroom access for ${s.name}`);showModule('staff');toast('Access revoked');});}
  function revokeStaffSessions(username){if(!has(CAP.STAFF_REVOKE))return;const sessions=read(KEYS.sessions,{});sessions[username]=[];write(KEYS.sessions,sessions);audit(`${currentUser().name} revoked active sessions for ${staffRecord(username)?.name||username}`);toast('Sessions revoked');}
  function togglePremium(id){if(!has(CAP.PREMIUM_ASSIGN))return;const list=getStories(),s=list.find(x=>x.id===id);if(!s)return;s.premium=!s.premium;s.updated=stamp();setStories(list);syncPremium(s);audit(`${currentUser().name} changed “${s.title}” access to ${s.premium?'Premium':'Public'}`);showModule('premium');toast(`Story is now ${s.premium?'Premium':'Public'}`);}

  function userPopover(){const el=$('[data-user-popover]'),u=currentUser();el.hidden=!el.hidden;if(!el.hidden)el.innerHTML=`<div class="nr-popover-id"><strong>${esc(u.name)}</strong><span>${esc(u.role)} · ${esc(u.desk)}</span></div><button data-popover-action="profile">My profile</button><button data-module-jump="my-assignments">My assignments</button><button data-module-jump="my-stories">My drafts & stories</button><button data-module-jump="security">Security</button><button data-sign-out>Sign out</button>`;}
  function openSearch(){const modal=$('[data-search-modal]');modal.hidden=false;const input=$('[data-newsroom-search-input]');input.value='';$('[data-newsroom-search-results]').innerHTML='';setTimeout(()=>input.focus(),20);}
  function searchNewsroom(q){q=q.trim().toLowerCase();if(!q){$('[data-newsroom-search-results]').innerHTML='';return;}const rs=[...getStories().filter(s=>`${s.title} ${s.desk} ${s.status}`.toLowerCase().includes(q)).slice(0,6).map(s=>({title:s.title,meta:`Story · ${s.status} · ${s.desk}`})),...getStaff().filter(s=>`${s.name} ${s.role} ${s.desk}`.toLowerCase().includes(q)).slice(0,4).map(s=>({title:s.name,meta:`Staff · ${s.role} · ${s.desk}`})),...getAssignments().filter(a=>`${a.title} ${a.desk}`.toLowerCase().includes(q)).slice(0,4).map(a=>({title:a.title,meta:`Assignment · ${a.status} · ${a.desk}`}))];$('[data-newsroom-search-results]').innerHTML=rs.map(r=>`<div class="nr-search-result"><strong>${esc(r.title)}</strong><span>${esc(r.meta)}</span></div>`).join('')||'<div class="nr-empty"><p>No matches found.</p></div>';}

  function filterStories(){const q=String($('[data-story-search]')?.value||'').toLowerCase(),st=$('[data-story-status]')?.value||'',desk=$('[data-story-desk]')?.value||'';const list=getStories().filter(s=>(!q||`${s.title} ${s.section} ${s.author}`.toLowerCase().includes(q))&&(!st||s.status===st)&&(!desk||s.desk===desk));$('[data-story-table]').innerHTML=storyTable(list);}

  function bindGlobal(){
    const loginForm=$('[data-login-form]');if(loginForm)loginForm.addEventListener('submit',e=>{e.preventDefault();const d=new FormData(loginForm);if(login(d.get('username'),d.get('password')))location.reload();else $('[data-login-error]').textContent='We could not sign you in. Check your staff credentials or access status.';});
    document.addEventListener('click',e=>{
      const mod=e.target.closest('[data-module]');if(mod){showModule(mod.dataset.module);return;}
      const jump=e.target.closest('[data-module-jump]');if(jump){showModule(jump.dataset.moduleJump);$('[data-user-popover]')?.setAttribute('hidden','');return;}
      if(e.target.closest('[data-sign-out]')){logout();return;}
      if(e.target.closest('[data-user-menu]')){userPopover();return;}
      if(e.target.closest('[data-quick-create]')){openStory();return;}
      const open=e.target.closest('[data-open-story]');if(open){openStory(open.dataset.openStory);return;}
      if(e.target.closest('[data-story-modal-close]')){closeStory();return;}
      if(e.target.closest('[data-manual-save]')){saveStory(true);return;}
      if(e.target.closest('[data-editor-primary]')){primaryEditorAction();return;}
      if(e.target.closest('[data-story-preview]')){flushAutosave();toast('Preview saved. Public preview opens after production CMS integration.');return;}
      const trans=e.target.closest('[data-transition-story]');if(trans){transitionStory(trans.dataset.transitionStory,trans.dataset.next);return;}
      const ap=e.target.closest('[data-assignment-progress]');if(ap){assignmentProgress(ap.dataset.assignmentProgress);return;}
      if(e.target.closest('[data-open-assignment]')){openAssignment();return;}
      if(e.target.closest('[data-assignment-close]')){$('[data-assignment-modal]').hidden=true;return;}
      if(e.target.closest('[data-open-invite]')){openInvite();return;}
      if(e.target.closest('[data-invite-close]')){$('[data-invite-modal]').hidden=true;return;}
      const sr=e.target.closest('[data-staff-role]');if(sr){changeStaffRole(sr.dataset.staffRole);return;}
      const ss=e.target.closest('[data-staff-sessions]');if(ss){revokeStaffSessions(ss.dataset.staffSessions);return;}
      const rv=e.target.closest('[data-staff-revoke]');if(rv){revokeAccess(rv.dataset.staffRevoke);return;}
      const pt=e.target.closest('[data-v21-premium-toggle]');if(pt){togglePremium(pt.dataset.v21PremiumToggle);return;}
      if(e.target.closest('[data-confirm-cancel]')){$('[data-confirm-modal]').hidden=true;pendingConfirm=null;return;}
      if(e.target.closest('[data-confirm-accept]')){const fn=pendingConfirm;$('[data-confirm-modal]').hidden=true;pendingConfirm=null;if(fn)fn();return;}
      if(e.target.closest('[data-global-search]')){openSearch();return;}
      if(e.target.closest('[data-search-close]')){$('[data-search-modal]').hidden=true;return;}
      if(e.target.closest('[data-notifications]')){showModule('overview');toast('Notifications are shown in your workspace.');return;}
      if(e.target.closest('[data-sidebar-open]')){$('[data-newsroom-sidebar]').classList.add('open');return;}
      if(e.target.closest('[data-sidebar-close]')){$('[data-newsroom-sidebar]').classList.remove('open');return;}
      const ins=e.target.closest('[data-insert]');if(ins){toast(`${ins.dataset.insert} placeholder added to the reporting workflow.`);return;}
    });
    document.addEventListener('input',e=>{if(e.target.closest('[data-story-form]')||e.target.getAttribute('form')==='story-shadow')scheduleAutosave();if(e.target.matches('[data-story-search],[data-story-status],[data-story-desk]'))filterStories();if(e.target.matches('[data-newsroom-search-input]'))searchNewsroom(e.target.value);});
    $('[data-assignment-form]')?.addEventListener('submit',e=>{e.preventDefault();saveAssignment(e.currentTarget);});
    $('[data-invite-form]')?.addEventListener('submit',e=>{e.preventDefault();saveInvite(e.currentTarget);});
    $('[data-comment-form]')?.addEventListener('submit',e=>{e.preventDefault();if(!editingStoryId)return;const text=e.currentTarget.elements.comment.value.trim();if(!text)return;const map=read(KEYS.comments,{});map[editingStoryId]=[...(map[editingStoryId]||[]),{id:`c-${Date.now()}`,user:currentUser().name,at:iso(),text,resolved:false}];write(KEYS.comments,map);audit(`${currentUser().name} added an editorial comment`);e.currentTarget.reset();renderComments(getStories().find(x=>x.id===editingStoryId));});
    window.addEventListener('beforeunload',()=>flushAutosave());
  }

  init();
})();
