(() => {
  'use strict';

  const SESSION_KEY='htpNewsroomSession';
  const STORIES_KEY='htpNewsroomStories';
  const AUDIT_KEY='htpNewsroomAudit';
  const BRIEFING_KEY='htpNewsroomBriefings';
  const WHATSAPP_DESK='263776280754';

  const accounts={
    publisher:{password:'HealthTimes#Publisher26',name:'Publisher Office',role:'Publisher / Owner',initials:'PO'},
    editor:{password:'HealthTimes#Editor26',name:'Michael Gwarisa',role:'Editor-in-Chief',initials:'MG'},
    reporter:{password:'HealthTimes#Reporter26',name:'Kuda Pembere',role:'Reporter / Journalist',initials:'KP'},
    audience:{password:'HealthTimes#Audience26',name:'Audience Desk',role:'Newsletter Editor',initials:'AD'},
    commercial:{password:'HealthTimes#Commercial26',name:'Commercial Desk',role:'Commercial Manager',initials:'CD'}
  };

  const roleDefinitions=[
    ['Publisher / Owner','Organisation-wide governance, business oversight and final administrative authority.',['All newsroom modules','Publish and archive','Manage staff roles','Commercial and subscriber oversight']],
    ['Editor-in-Chief','Editorial policy, final publication authority and newsroom standards.',['Review all editorial work','Publish and correct','Assign editors','View audience analytics']],
    ['Managing Editor','Daily newsroom operations and production planning.',['Assignments and calendar','Review queues','Edit across sections','Schedule publication']],
    ['Section Editor','Editorial authority within an assigned section.',['Assign section stories','Edit section copy','Submit for publication','Review section workflow']],
    ['News Editor','Daily news desk and breaking-news coordination.',['Manage breaking queue','Edit news copy','Coordinate assignments','Schedule news']],
    ['Reporter / Journalist','Reporting, drafting and source development.',['Create stories','Edit own/assigned drafts','Add sources and notes','Submit for review']],
    ['Health / Science Editor','Specialist health and evidence review.',['Review medical/science claims','Check evidence context','Return for revision','Approve specialist review']],
    ['Fact Checker','Verification of material facts and sources.',['Review source notes','Mark checks complete','Flag unsupported claims','No direct publishing']],
    ['Copy Editor','Language, structure, headlines and house style.',['Edit assigned copy','Headline and style review','Prepare ready state','No user administration']],
    ['Multimedia Editor','Images, video, audio and visual storytelling.',['Manage media','Attach assets','Edit captions/credits','No editorial publishing']],
    ['Social Editor','Distribution across social channels.',['Prepare social posts','Schedule distribution','View published stories','No article body edits']],
    ['Newsletter Editor','Email and WhatsApp editorial editions.',['Build briefings','Select published stories','Preview/send channels','View audience preferences']],
    ['Commercial Manager','Commercial inventory and sponsorship, separated from editorial decisions.',['Manage commercial placements','View Premium proposition','View aggregate analytics','Cannot edit editorial copy']],
    ['Subscriber Manager','Membership service and subscriber operations.',['View subscriber service','Manage support status','View Premium access','Cannot edit editorial copy']],
    ['Analyst','Read-only performance and trend reporting.',['Read analytics','Read published inventory','Export reporting views','No content mutation']]
  ];

  const moduleGroups=[
    ['Editorial',[['overview','Overview','⌂'],['stories','Stories','▤'],['assignments','Assignments','✓'],['calendar','Editorial Calendar','□'],['review','Review Queue','◫'],['media','Media','▧'],['authors','Authors','◎'],['topics','Topics','#'],['breaking','Breaking News','!']]],
    ['Products',[['premium','Premium','◆'],['ai','AI Desk','✦']]],
    ['Audience',[['audience','Audience','◉'],['newsletter','Newsletter','✉'],['whatsapp','WhatsApp','W'],['subscribers','Subscribers','♙'],['analytics','Analytics','↗']]],
    ['Administration',[['staff','Staff & Roles','♟'],['settings','Settings','⚙']]]
  ];

  const permissions={
    'Publisher / Owner':{modules:'all',create:true,editAll:true,publish:true,roles:true,audience:true,commercial:true},
    'Editor-in-Chief':{modules:['overview','stories','assignments','calendar','review','media','authors','topics','breaking','premium','ai','audience','newsletter','whatsapp','analytics','staff','settings'],create:true,editAll:true,publish:true,roles:false,audience:true},
    'Reporter / Journalist':{modules:['overview','stories','assignments','calendar','media','ai','settings'],create:true,editOwn:true,publish:false},
    'Newsletter Editor':{modules:['overview','audience','newsletter','whatsapp','analytics','settings'],create:false,editAll:false,publish:false,audience:true},
    'Commercial Manager':{modules:['overview','premium','audience','subscribers','analytics','settings'],create:false,editAll:false,publish:false,commercial:true}
  };

  const initialStories=[
    {id:'s1',title:'Parliament Probes NatPharm Over Zimbabwe’s Medicine Supply Chain',section:'Health Policy',type:'News',premium:false,owner:'editor',author:'Michael Gwarisa',editor:'News Desk',status:'Published',updated:'2026-09-07 08:30',standfirst:'Parliament resumes scrutiny of medicines procurement and distribution.',notes:'Published. Primary institutional source: Parliamentary Portfolio Committee on Health and Child Care.'},
    {id:'s2',title:'Harare STI Cases Fall Below 2,000 Per Quarter, NAC Says',section:'Public Health',type:'News',premium:false,owner:'reporter',author:'Kuda Pembere',editor:'Michael Gwarisa',status:'Published',updated:'2026-09-07 09:10',standfirst:'NAC reports a decline while warning of the continued burden among young women.',notes:'Published. Primary source: National AIDS Council.'},
    {id:'s3',title:'Healthathon 3.0: What Zimbabwe’s Health Innovation Challenge Is Telling Us',section:'Opinion & Analysis',type:'Analysis',premium:false,owner:'editor',author:'Michael Gwarisa',editor:'Opinion Desk',status:'Published',updated:'2026-09-07 12:05',standfirst:'Analysis of the expanding health-innovation ecosystem.',notes:'Published analysis.'},
    {id:'s4',title:'Medicine Supply Dashboard: What the NatPharm Inquiry Should Measure Next',section:'Health Policy',type:'Analysis',premium:true,owner:'editor',author:'Michael Gwarisa',editor:'Policy & Analysis Desk',status:'Ready',updated:'2026-09-09 08:40',standfirst:'A proposed accountability framework for tracking medicines from financing to facilities.',notes:'Sources verified. Awaiting final Editor-in-Chief approval.'},
    {id:'s5',title:'Community Prevention Follow-up: What Harare’s STI Trend Does Not Yet Tell Us',section:'Public Health',type:'Analysis',premium:true,owner:'reporter',author:'Kuda Pembere',editor:'Michael Gwarisa',status:'Review',updated:'2026-09-09 09:05',standfirst:'A follow-up examining age, reporting periods and prevention programme evidence.',notes:'Reporter submitted. Needs editor review and data-context check.'},
    {id:'s6',title:'Weekly Africa Outbreak Watch',section:'Africa',type:'Live / Developing',premium:false,owner:'reporter',author:'Kuda Pembere',editor:'News Desk',status:'Draft',updated:'2026-09-09 09:30',standfirst:'A developing regional health surveillance briefing.',notes:'Working draft. Add Africa CDC update and confirm case-date cut-off before review.'},
    {id:'s7',title:'National Health Strategy: Implementation Tracker',section:'Health Policy',type:'Feature',premium:true,owner:'editor',author:'Michael Gwarisa',editor:'Policy & Analysis Desk',status:'Fact check',updated:'2026-09-09 10:00',standfirst:'A living tracker of implementation commitments under the 2026–2030 strategy.',notes:'Fact checker to verify ministry milestones and source documents.'},
    {id:'s8',title:'Friday HealthTimes Weekly',section:'Health News',type:'Feature',premium:false,owner:'audience',author:'Audience Desk',editor:'Newsletter Desk',status:'Scheduled',updated:'2026-09-09 10:10',standfirst:'The week’s essential health reporting in one concise edition.',notes:'Scheduled for Friday distribution after final story selection.'}
  ];

  const $=(s,r=document)=>r.querySelector(s);const $$=(s,r=document)=>[...r.querySelectorAll(s)];
  function read(key,fallback){try{const v=localStorage.getItem(key);return v?JSON.parse(v):fallback}catch{return fallback}}
  function write(key,value){try{localStorage.setItem(key,JSON.stringify(value))}catch{}}
  function esc(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
  function getStories(){const s=read(STORIES_KEY,null);if(s)return s;write(STORIES_KEY,initialStories);return [...initialStories]}
  function setStories(stories){write(STORIES_KEY,stories)}
  function getSession(){return read(SESSION_KEY,null)}
  function perm(){const u=currentUser();return u?permissions[u.role]||{}:{}}
  function currentUser(){const s=getSession();if(!s||!accounts[s.username])return null;return {...accounts[s.username],username:s.username}}
  function canModule(id){const p=perm();return p.modules==='all'||(Array.isArray(p.modules)&&p.modules.includes(id))}
  function canEdit(story){const u=currentUser(),p=perm();return !!(u&&(p.editAll||(p.editOwn&&story.owner===u.username)))}
  function canCreate(){return !!perm().create}
  function canPublish(){return !!perm().publish}
  function nowLabel(){return new Date().toISOString().slice(0,16).replace('T',' ')}
  function initials(name){return name.split(/\s+/).map(x=>x[0]).join('').slice(0,2).toUpperCase()}

  let activeModule='overview';let pendingConfirm=null;

  function login(username,password){const key=username.trim().toLowerCase();const account=accounts[key];if(!account||account.password!==password)return false;write(SESSION_KEY,{username:key,signedInAt:new Date().toISOString()});addAudit(`${account.name} signed in`);return true}
  function signOut(){const u=currentUser();if(u)addAudit(`${u.name} signed out`);try{localStorage.removeItem(SESSION_KEY)}catch{};location.reload()}
  function addAudit(action){const u=currentUser();const list=read(AUDIT_KEY,[]);list.unshift({at:new Date().toISOString(),user:u?u.name:'Newsroom',role:u?u.role:'System',action});write(AUDIT_KEY,list.slice(0,80))}

  function init(){
    const user=currentUser();
    if(!user){$('[data-login-view]').hidden=false;$('[data-newsroom-app]').hidden=true;return}
    $('[data-login-view]').hidden=true;$('[data-newsroom-app]').hidden=false;
    renderNav();renderUser();showModule(firstAllowed(activeModule));bindWorkspaceEvents();
  }
  function firstAllowed(preferred){if(canModule(preferred))return preferred;for(const [,mods] of moduleGroups){for(const [id] of mods){if(canModule(id))return id}}return 'settings'}

  function renderNav(){const nav=$('[data-newsroom-nav]');nav.innerHTML=moduleGroups.map(([group,mods])=>{const visible=mods.filter(([id])=>canModule(id));if(!visible.length)return'';return `<div class="nav-group-label">${esc(group)}</div>${visible.map(([id,label,icon])=>`<button type="button" data-module="${id}" class="${activeModule===id?'active':''}"><span>${icon}</span><span>${esc(label)}</span></button>`).join('')}`}).join('')}
  function renderUser(){const u=currentUser();$('[data-user-mini]').innerHTML=`<strong>${esc(u.name)}</strong><span>${esc(u.role)}</span><button type="button" data-sign-out>Sign out</button>`;$('[data-user-menu]').textContent=u.initials||initials(u.name);$('[data-topline]').textContent=`${u.name} · ${u.role}`}
  function setBreadcrumb(label){$('[data-breadcrumb]').textContent=label}

  function showModule(id){
    if(!canModule(id)){toast('Your role does not have access to that module.');return}
    activeModule=id;renderNav();const label=moduleGroups.flatMap(g=>g[1]).find(x=>x[0]===id)?.[1]||id;setBreadcrumb(label);const workspace=$('[data-workspace]');
    const renderers={overview:renderOverview,stories:renderStories,assignments:renderAssignments,calendar:renderCalendar,review:renderReview,media:renderMedia,authors:renderAuthors,topics:renderTopics,breaking:renderBreaking,premium:renderPremium,ai:renderAi,audience:renderAudience,newsletter:renderNewsletter,whatsapp:renderWhatsApp,subscribers:renderSubscribers,analytics:renderAnalytics,staff:renderStaff,settings:renderSettings};
    workspace.innerHTML=(renderers[id]||renderOverview)();
  }

  function heading(title,copy,actions=''){return `<div class="workspace-heading"><div><span class="eyebrow">HealthTimes Newsroom</span><h1>${esc(title)}</h1><p>${esc(copy)}</p></div><div class="workspace-actions">${actions}</div></div>`}
  function statusClass(s){const x=s.toLowerCase();if(x==='published')return'published';if(x==='review')return'review';if(x==='draft')return'draft';if(x==='fact check')return'fact-check';if(x==='ready')return'ready';return''}
  function storyRows(list){const u=currentUser();return list.map(s=>`<tr><td class="story-title-cell"><strong>${esc(s.title)}</strong><span>${esc(s.type)} · ${s.premium?'Premium':'Public'}</span></td><td>${esc(s.section)}</td><td>${esc(s.author)}</td><td><span class="workflow-status ${statusClass(s.status)}">${esc(s.status)}</span></td><td>${esc(s.updated)}</td><td><div class="table-actions"><button type="button" data-edit-story="${s.id}" ${canEdit(s)?'':'disabled'}>Edit</button>${nextActionButton(s,u)}</div></td></tr>`).join('')}
  function nextActionButton(story,user){
    if(!canEdit(story)&&!canPublish())return'';
    if(story.status==='Published')return canPublish()?`<button type="button" data-story-transition="${story.id}" data-next="Correction/Update">Update</button>`:'';
    if(story.status==='Draft'&&story.owner===user.username)return `<button type="button" data-story-transition="${story.id}" data-next="Review">Submit</button>`;
    if(story.status==='Review'&&canPublish())return `<button type="button" data-story-transition="${story.id}" data-next="Fact check">Send to fact check</button>`;
    if(story.status==='Fact check'&&canPublish())return `<button type="button" data-story-transition="${story.id}" data-next="Ready">Mark verified</button>`;
    if((story.status==='Ready'||story.status==='Scheduled')&&canPublish())return `<button class="primary" type="button" data-story-transition="${story.id}" data-next="Published">Publish</button>`;
    if(story.status==='Correction/Update'&&canPublish())return `<button type="button" data-story-transition="${story.id}" data-next="Published">Publish update</button>`;
    return'';
  }

  function renderOverview(){const stories=getStories(),review=stories.filter(s=>['Review','Fact check','Ready'].includes(s.status)),published=stories.filter(s=>s.status==='Published');return `${heading('Overview','The newsroom at a glance.',canCreate()?'<button class="primary" type="button" data-quick-create>＋ New story</button>':'')}<div class="permission-note"><strong>${esc(currentUser().role)}</strong> access is active. Actions outside this role are unavailable in the workspace.</div><div class="metric-grid"><article class="metric-card"><span>Stories in workflow</span><strong>${stories.filter(s=>s.status!=='Published').length}</strong><small>Across draft, review and scheduling</small></article><article class="metric-card"><span>Needs review</span><strong>${review.length}</strong><small>Editorial or verification action</small></article><article class="metric-card"><span>Published in dataset</span><strong>${published.length}</strong><small>Available to the public product</small></article><article class="metric-card"><span>Audience channels</span><strong>3</strong><small>Email · WhatsApp · browser</small></article></div><div class="dashboard-grid"><section class="newsroom-panel"><div class="panel-head"><div><h2>Publishing pipeline</h2><p>Current working inventory by state</p></div></div><div class="pipeline">${['Draft','Review','Fact check','Ready','Scheduled'].map(st=>`<div class="pipeline-stage"><span>${st}</span><strong>${stories.filter(s=>s.status===st).length}</strong></div>`).join('')}</div></section><section class="newsroom-panel"><div class="panel-head"><div><h2>Priority queue</h2><p>Items closest to a newsroom decision</p></div></div><ul class="queue-list">${review.slice(0,4).map(s=>`<li class="queue-item"><div><h3>${esc(s.title)}</h3><p>${esc(s.status)} · ${esc(s.author)}</p></div><button type="button" data-module="stories">Open</button></li>`).join('')||'<li class="empty-state">No items in review.</li>'}</ul></section></div><section class="newsroom-panel"><div class="panel-head"><div><h2>Recent newsroom activity</h2><p>Account-level action record</p></div></div>${auditHtml()}</section>`}

  function renderStories(){const action=canCreate()?'<button class="primary" type="button" data-quick-create>＋ New story</button>':'';return `${heading('Stories','Create, edit, review and publish through a controlled editorial lifecycle.',action)}<section class="newsroom-panel"><div class="filter-bar"><input data-story-filter placeholder="Search headlines or authors…" /><select data-status-filter><option value="">All workflow states</option>${['Draft','Review','Fact check','Ready','Scheduled','Published','Correction/Update'].map(x=>`<option>${x}</option>`).join('')}</select></div><div class="story-table-wrap"><table class="story-table"><thead><tr><th>Story</th><th>Section</th><th>Author</th><th>Status</th><th>Updated</th><th>Actions</th></tr></thead><tbody data-story-table>${storyRows(getStories())}</tbody></table></div></section>`}

  function renderAssignments(){const stories=getStories().filter(s=>s.status!=='Published');return `${heading('Assignments','Track who owns each story, its editor and the next required step.',canCreate()?'<button class="primary" type="button" data-quick-create>New assignment</button>':'')}<section class="newsroom-panel"><div class="panel-head"><div><h2>Active assignments</h2><p>Ownership is explicit; reporters edit only their own or assigned work.</p></div></div><ul class="queue-list">${stories.map(s=>`<li class="queue-item"><div><h3>${esc(s.title)}</h3><p>Author: ${esc(s.author)} · Editor: ${esc(s.editor||'Unassigned')} · ${esc(s.status)}</p></div>${canEdit(s)?`<button type="button" data-edit-story="${s.id}">Open workspace</button>`:'<span class="workflow-status">Read only</span>'}</li>`).join('')}</ul></section>`}

  function renderCalendar(){const stories=getStories();const days=['Mon 7','Tue 8','Wed 9','Thu 10','Fri 11','Sat 12','Sun 13'];return `${heading('Editorial Calendar','Plan publication, briefings and developing coverage across the week.')}<section class="newsroom-panel"><div class="panel-head"><div><h2>Week of September 7</h2><p>Scheduled and active newsroom work</p></div></div><div class="calendar-grid">${days.map((d,i)=>`<div class="calendar-cell"><span>${d}</span>${stories.filter((_,idx)=>idx%7===i).slice(0,2).map(s=>`<div class="calendar-story">${esc(s.title)}<br><small>${esc(s.status)}</small></div>`).join('')}</div>`).join('')}</div></section>`}

  function renderReview(){const review=getStories().filter(s=>['Review','Fact check','Ready'].includes(s.status));return `${heading('Review Queue','Editorial, verification and final-approval work awaiting action.')}<section class="newsroom-panel"><div class="panel-head"><div><h2>Current queue</h2><p>Only roles with appropriate authority can advance these stories.</p></div></div><ul class="queue-list">${review.map(s=>`<li class="queue-item"><div><h3>${esc(s.title)}</h3><p>${esc(s.status)} · ${esc(s.section)} · ${esc(s.author)}</p></div>${canEdit(s)||canPublish()?`<button type="button" data-module="stories">Review</button>`:'<span class="workflow-status">Read only</span>'}</li>`).join('')||'<li class="empty-state"><h3>Queue clear</h3><p>No stories currently require review.</p></li>'}</ul></section>`}

  function renderMedia(){return `${heading('Media','Manage images, video, audio, captions, credits and story attachments.')}<section class="newsroom-panel"><div class="panel-head"><div><h2>Media library</h2><p>Editorial assets remain linked to story ownership and usage context.</p></div>${canCreate()?'<button type="button" data-simulate="media">Upload media</button>':''}</div><div class="role-matrix"><article class="role-card"><span class="eyebrow">Images</span><h3>Story photography</h3><p>Hero images, captions, source credit and alt text.</p></article><article class="role-card"><span class="eyebrow">Video</span><h3>Field and interview clips</h3><p>Short-form newsroom video and embedded reporting.</p></article><article class="role-card"><span class="eyebrow">Documents</span><h3>Source files</h3><p>Policy documents, reports and supporting public records.</p></article></div></section>`}

  function renderAuthors(){const staff=[['Michael Gwarisa','Editor-in-Chief','Health policy, systems and accountability'],['Kudakwashe Pembere','Assistant Editor','Public health and daily news'],['Ntokozo Gudu','Reporter','Health reporting'],['Patson Gumbo','Reporter','Health reporting'],['Rukudzo Gota','Reporter','Health reporting']];return `${heading('Authors','Public accountability and internal assignment profiles for the people behind HealthTimes reporting.')}<section class="newsroom-panel"><div class="staff-list">${staff.map(s=>`<article class="staff-card"><span class="staff-avatar">${initials(s[0])}</span><div><strong>${esc(s[0])}</strong><span>${esc(s[1])} · ${esc(s[2])}</span></div></article>`).join('')}</div></section>`}

  function renderTopics(){const topics=['Public Health','HIV/AIDS','Health Policy','Health Financing','Medical Research','Mental Health','Medicines','Innovation','Africa Health','Global Health'];return `${heading('Topics','Maintain beats that power navigation, alerts, briefings and HealthTimes Intelligence.')}<section class="newsroom-panel"><div class="role-matrix">${topics.map((t,i)=>`<article class="role-card"><span class="eyebrow">Topic hub ${String(i+1).padStart(2,'0')}</span><h3>${esc(t)}</h3><p>Connect reporting, explainers, related coverage and reader preferences.</p></article>`).join('')}</div></section>`}

  function renderBreaking(){const breaking=getStories().filter(s=>s.type==='Live / Developing'||s.section==='Health News').slice(0,4);return `${heading('Breaking News','Coordinate urgent and developing health coverage without bypassing verification.')}<div class="permission-note"><strong>Breaking does not mean unverified.</strong> Source confirmation and clear timestamps remain required before publication.</div><section class="newsroom-panel"><ul class="queue-list">${breaking.map(s=>`<li class="queue-item"><div><h3>${esc(s.title)}</h3><p>${esc(s.status)} · Last touched ${esc(s.updated)}</p></div>${canEdit(s)?`<button type="button" data-edit-story="${s.id}">Open</button>`:'<span class="workflow-status">Read only</span>'}</li>`).join('')}</ul></section>`}

  function renderPremium(){const premium=getStories().filter(s=>s.premium);return `${heading('Premium','Manage the member reporting proposition separately from normal public-story access.','<a href="premium.html" target="_blank">View Premium ↗</a>')}<div class="metric-grid"><article class="metric-card"><span>Membership</span><strong>US$5</strong><small>Monthly proposition</small></article><article class="metric-card"><span>Premium stories</span><strong>${premium.length}</strong><small>In current newsroom dataset</small></article><article class="metric-card"><span>Intro preview</span><strong>30s</strong><small>Reader sampling window</small></article><article class="metric-card"><span>Member briefing</span><strong>Weekly</strong><small>Intelligence edition</small></article></div><section class="newsroom-panel"><div class="panel-head"><div><h2>Premium editorial inventory</h2><p>Premium status is an editorial/product attribute, not a substitute for normal review.</p></div></div><div class="story-table-wrap"><table class="story-table"><thead><tr><th>Story</th><th>Section</th><th>Author</th><th>Status</th><th>Updated</th><th>Actions</th></tr></thead><tbody>${storyRows(premium)}</tbody></table></div></section>`}

  function renderAi(){return `${heading('AI Desk','Govern how Ask HealthTimes uses published reporting and how editors review AI-assisted workflows.','<a href="index.html" target="_blank">Open Ask HealthTimes ↗</a>')}<div class="permission-note"><strong>Editorial boundary:</strong> HealthTimes Intelligence may help readers navigate and understand reporting, but it must not diagnose, prescribe medication or replace a clinician. Editors remain accountable for published journalism.</div><div class="dashboard-grid"><section class="newsroom-panel"><div class="panel-head"><div><h2>Approved reader capabilities</h2><p>Current public assistant behaviors</p></div></div><ul class="queue-list"><li class="queue-item"><div><h3>Story summary</h3><p>Grounded in the open HealthTimes article.</p></div><span class="workflow-status published">Active</span></li><li class="queue-item"><div><h3>Why it matters</h3><p>Uses editorial significance/context fields.</p></div><span class="workflow-status published">Active</span></li><li class="queue-item"><div><h3>Related coverage</h3><p>Surfaces matching HealthTimes stories by beat and tags.</p></div><span class="workflow-status published">Active</span></li><li class="queue-item"><div><h3>Medical diagnosis or dosing</h3><p>Blocked by the health-information safety boundary.</p></div><span class="workflow-status fact-check">Blocked</span></li></ul></section><section class="newsroom-panel"><div class="panel-head"><div><h2>Production controls</h2><p>Required before live AI integration</p></div></div><ul class="queue-list"><li class="queue-item"><div><h3>Authoritative CMS retrieval</h3><p>Server-side RAG over published and permissioned sources.</p></div></li><li class="queue-item"><div><h3>Provenance and logging</h3><p>Track source citations and response quality.</p></div></li><li class="queue-item"><div><h3>Safety review</h3><p>Medical-risk handling and escalation policies.</p></div></li></ul></section></div>`}

  function renderAudience(){return `${heading('Audience','Coordinate reader preferences, feedback and distribution channels without mixing them with editorial authority.')}<div class="channel-cards"><article class="channel-card"><span>Email</span><strong>Configured</strong><small>Daily, weekly and research-digest editions</small></article><article class="channel-card"><span>WhatsApp</span><strong>Configured</strong><small>Direct desk plus reader briefing preference</small></article><article class="channel-card"><span>Browser</span><strong>Prepared</strong><small>Notification preference ready for service integration</small></article></div><section class="newsroom-panel"><div class="panel-head"><div><h2>Reader preference model</h2><p>Topic + frequency + channel</p></div><button type="button" data-open-public-prefs>Open reader view</button></div><div class="role-matrix"><article class="role-card"><h3>Topics</h3><p>Breaking news, HIV/AIDS, policy, research, mental health, maternal and child health, medicines, financing, innovation and Africa.</p></article><article class="role-card"><h3>Frequency</h3><p>Breaking, daily, weekly, Premium weekly intelligence and monthly research digest.</p></article><article class="role-card"><h3>Consent-aware delivery</h3><p>Production integration must store channel consent and unsubscribe state alongside the subscriber record.</p></article></div></section>`}

  function getBriefings(){return read(BRIEFING_KEY,[{id:'b1',title:'HealthTimes Weekly — September 11',channel:'Email + WhatsApp',status:'Draft',items:4},{id:'b2',title:'Premium Intelligence — Policy & Financing',channel:'Email',status:'Ready',items:3}])}
  function renderNewsletter(){const briefings=getBriefings();return `${heading('Newsletter','Build concise editions from approved and published HealthTimes reporting.','<button class="primary" type="button" data-simulate="briefing">＋ New briefing</button>')}<section class="newsroom-panel"><div class="panel-head"><div><h2>Briefing desk</h2><p>Only published/approved stories should be selected for reader delivery.</p></div></div><ul class="queue-list">${briefings.map(b=>`<li class="queue-item"><div><h3>${esc(b.title)}</h3><p>${esc(b.channel)} · ${b.items} stories · ${esc(b.status)}</p></div><button type="button" data-preview-briefing="${b.id}">Preview</button></li>`).join('')}</ul></section>`}

  function renderWhatsApp(){return `${heading('WhatsApp','Reader comments, newsroom contact and briefing distribution for a mobile-first audience.','<button class="primary" type="button" data-whatsapp-preview>Preview weekly message</button>')}<div class="dashboard-grid"><section class="newsroom-panel"><div class="panel-head"><div><h2>HealthTimes WhatsApp desk</h2><p>Publication-level contact rather than personal reporter numbers</p></div></div><div style="padding:18px"><p><strong>Primary:</strong> +263 77 628 0754</p><p><strong>Secondary:</strong> +263 772 679 680</p><p>Article comments arrive with the story title and URL prefilled so the desk can understand context immediately.</p><a class="button button-primary" href="https://wa.me/${WHATSAPP_DESK}?text=${encodeURIComponent('Hello HealthTimes newsroom')}" target="_blank" rel="noopener">Open WhatsApp desk</a></div></section><section class="newsroom-panel"><div class="panel-head"><div><h2>Channel rules</h2><p>Reader trust and consent</p></div></div><ul class="queue-list"><li class="queue-item"><div><h3>Comments & tips</h3><p>Route through publication contact, not private staff numbers.</p></div></li><li class="queue-item"><div><h3>Briefings</h3><p>Send only to readers who selected WhatsApp delivery.</p></div></li><li class="queue-item"><div><h3>Corrections</h3><p>Escalate factual correction requests to the editorial desk.</p></div></li></ul></section></div>`}

  function renderSubscribers(){return `${heading('Subscribers','Membership service view, deliberately separated from editorial copy controls.')}<div class="permission-note"><strong>Separation of duties:</strong> subscriber and commercial roles can support membership operations but cannot silently change article content or editorial approval history.</div><section class="newsroom-panel"><div class="panel-head"><div><h2>Production membership fields</h2><p>Data model prepared for future billing/authentication connection</p></div></div><div class="role-matrix"><article class="role-card"><h3>Identity</h3><p>Account ID, verified email/phone, authentication status and consent.</p></article><article class="role-card"><h3>Entitlement</h3><p>Plan, active period, renewal state and server-authorised Premium access.</p></article><article class="role-card"><h3>Preferences</h3><p>Topic follows, email/WhatsApp delivery and unsubscribe state.</p></article></div></section>`}

  function renderAnalytics(){const stories=getStories();const sections={};stories.forEach(s=>sections[s.section]=(sections[s.section]||0)+1);const max=Math.max(...Object.values(sections));return `${heading('Analytics','Editorial operations are populated from the newsroom dataset; production reach metrics will connect to a privacy-aware analytics pipeline.')}<div class="dashboard-grid"><section class="newsroom-panel"><div class="panel-head"><div><h2>Editorial mix</h2><p>Current story inventory by section</p></div></div><div class="insight-bars">${Object.entries(sections).map(([name,count])=>`<div class="insight-row"><span>${esc(name)}</span><div class="bar-track"><div class="bar-fill" style="width:${Math.round(count/max*100)}%"></div></div><strong>${count}</strong></div>`).join('')}</div></section><section class="newsroom-panel"><div class="panel-head"><div><h2>Reader metrics</h2><p>Production connection boundary</p></div></div><div class="empty-state"><h3>Analytics connector ready</h3><p>Reach, scroll depth, Premium conversion, newsletter engagement and referral channels should come from the production analytics service rather than fabricated values.</p></div></section></div>`}

  function renderStaff(){if(!canModule('staff'))return'';return `${heading('Staff & Roles','Define newsroom responsibilities while keeping accounts isolated and commercial authority separate from editorial authority.')}<div class="permission-note"><strong>No impersonation:</strong> staff sessions are account-specific. Passwords are never displayed in the staff directory, and role boundaries determine available modules and actions.</div><section class="newsroom-panel"><div class="panel-head"><div><h2>Role matrix</h2><p>HealthTimes editorial and operational positions</p></div></div><div class="role-matrix">${roleDefinitions.map(([name,copy,caps])=>`<article class="role-card"><span class="eyebrow">Role</span><h3>${esc(name)}</h3><p>${esc(copy)}</p><ul>${caps.map(c=>`<li>${esc(c)}</li>`).join('')}</ul></article>`).join('')}</div></section><section class="newsroom-panel"><div class="panel-head"><div><h2>Active presentation accounts</h2><p>Passwords remain private to the account holder.</p></div></div><div class="staff-list">${Object.entries(accounts).map(([username,a])=>`<article class="staff-card"><span class="staff-avatar">${a.initials}</span><div><strong>${esc(a.name)}</strong><span>${esc(a.role)} · @${esc(username)}</span></div></article>`).join('')}</div></section>`}

  function renderSettings(){const u=currentUser();return `${heading('Settings','Account-specific newsroom preferences and production integration boundaries.')}<div class="dashboard-grid"><section class="newsroom-panel"><div class="panel-head"><div><h2>Your account</h2><p>Current isolated newsroom session</p></div></div><div style="padding:18px"><p><strong>${esc(u.name)}</strong><br><span style="color:var(--muted)">${esc(u.role)} · @${esc(u.username)}</span></p><p>Your role controls visible modules and available editorial actions. Another staff account cannot be opened without signing out and authenticating again.</p><button class="button button-ghost" type="button" data-sign-out>Sign out</button></div></section><section class="newsroom-panel"><div class="panel-head"><div><h2>Production security</h2><p>Required before operational launch</p></div></div><ul class="queue-list"><li class="queue-item"><div><h3>Managed authentication + MFA</h3><p>Replace browser-local presentation accounts.</p></div></li><li class="queue-item"><div><h3>Server-side RBAC</h3><p>Enforce permissions on every content and administrative mutation.</p></div></li><li class="queue-item"><div><h3>Immutable audit history</h3><p>Persist revisions, approvals, corrections and security events.</p></div></li></ul></section></div>`}

  function auditHtml(){const list=read(AUDIT_KEY,[]);return `<ul class="audit-list">${(list.length?list:[{at:new Date().toISOString(),user:'Newsroom',role:'System',action:'Newsroom workspace ready'}]).slice(0,8).map(x=>`<li><time>${new Date(x.at).toLocaleString()}</time><span><strong>${esc(x.user)}</strong> · ${esc(x.action)}</span></li>`).join('')}</ul>`}

  function openStoryModal(id=''){
    if(!canCreate()&&!id){toast('Your role cannot create stories.');return}
    const modal=$('[data-story-modal]'),form=$('[data-story-form]');let story=id?getStories().find(s=>s.id===id):null;if(story&&!canEdit(story)){toast('This story is read-only for your role.');return}
    modal.hidden=false;$('[data-story-modal-title]').textContent=story?'Edit story':'New story';form.reset();form.id.value=story?.id||'';form.title.value=story?.title||'';form.section.value=story?.section||'Health News';form.type.value=story?.type||'News';form.premium.value=String(story?.premium||false);form.editor.value=story?.editor||'';form.standfirst.value=story?.standfirst||'';form.notes.value=story?.notes||'';setTimeout(()=>form.title.focus(),80)
  }
  function closeStoryModal(){$('[data-story-modal]').hidden=true}
  function saveStory(form){const u=currentUser(),stories=getStories(),id=form.id.value||`s${Date.now()}`;const existing=stories.find(s=>s.id===id);const story={id,title:form.title.value.trim(),section:form.section.value,type:form.type.value,premium:form.premium.value==='true',owner:existing?.owner||u.username,author:existing?.author||u.name,editor:form.editor.value.trim()||existing?.editor||'Unassigned',status:existing?.status||'Draft',updated:nowLabel(),standfirst:form.standfirst.value.trim(),notes:form.notes.value.trim()};const next=existing?stories.map(s=>s.id===id?story:s):[story,...stories];setStories(next);addAudit(`${existing?'Updated':'Created'} story: ${story.title}`);closeStoryModal();toast(existing?'Story updated.':'Story created as Draft.');showModule('stories')}

  function transitionStory(id,next){const stories=getStories(),story=stories.find(s=>s.id===id);if(!story)return;const action=()=>{story.status=next;story.updated=nowLabel();setStories(stories);addAudit(`${story.title} → ${next}`);toast(`Story moved to ${next}.`);showModule(activeModule)};if(next==='Published'){openConfirm('Publish this story?',`“${story.title}” will move to Published and become part of the publication workflow record.`,action)}else action()}
  function openConfirm(title,copy,callback){pendingConfirm=callback;$('[data-confirm-title]').textContent=title;$('[data-confirm-copy]').textContent=copy;$('[data-confirm-modal]').hidden=false}
  function closeConfirm(){pendingConfirm=null;$('[data-confirm-modal]').hidden=true}

  function filterStoryTable(){if(activeModule!=='stories')return;const term=$('[data-story-filter]')?.value.toLowerCase()||'',status=$('[data-status-filter]')?.value||'';const list=getStories().filter(s=>(!term||`${s.title} ${s.author} ${s.section}`.toLowerCase().includes(term))&&(!status||s.status===status));const body=$('[data-story-table]');if(body)body.innerHTML=storyRows(list)}
  function previewBriefing(id){const b=getBriefings().find(x=>x.id===id);if(!b)return;const titles=getStories().filter(s=>s.status==='Published').slice(0,b.items).map(s=>s.title);openConfirm(b.title,`${b.channel}. ${titles.join(' • ')}`,()=>{closeConfirm();toast('Briefing preview closed without sending.')})}
  function openWhatsAppPreview(){const titles=getStories().filter(s=>s.status==='Published').slice(0,3).map(s=>`• ${s.title}`).join('\n');const msg=encodeURIComponent(`HealthTimes Weekly\n\n${titles}\n\nRead more: https://kudzimusar.github.io/htp-zw/`);window.open(`https://wa.me/?text=${msg}`,'_blank','noopener,noreferrer')}

  function bindWorkspaceEvents(){
    document.addEventListener('click',e=>{
      const module=e.target.closest('[data-module]');if(module){showModule(module.dataset.module);$('[data-newsroom-sidebar]').classList.remove('open');return}
      if(e.target.closest('[data-sidebar-open]')){$('[data-newsroom-sidebar]').classList.add('open');return}
      if(e.target.closest('[data-sidebar-close]')){$('[data-newsroom-sidebar]').classList.remove('open');return}
      if(e.target.closest('[data-sign-out]')){signOut();return}
      if(e.target.closest('[data-quick-create]')){openStoryModal();return}
      const edit=e.target.closest('[data-edit-story]');if(edit){openStoryModal(edit.dataset.editStory);return}
      const trans=e.target.closest('[data-story-transition]');if(trans){transitionStory(trans.dataset.storyTransition,trans.dataset.next);return}
      if(e.target.closest('[data-story-modal-close]')){closeStoryModal();return}
      if(e.target.closest('[data-confirm-cancel]')){closeConfirm();return}
      if(e.target.closest('[data-confirm-accept]')){const cb=pendingConfirm;closeConfirm();if(cb)cb();return}
      if(e.target.closest('[data-open-public-prefs]')){window.open('preferences.html','_blank','noopener');return}
      const briefing=e.target.closest('[data-preview-briefing]');if(briefing){previewBriefing(briefing.dataset.previewBriefing);return}
      if(e.target.closest('[data-whatsapp-preview]')){openWhatsAppPreview();return}
      const sim=e.target.closest('[data-simulate]');if(sim){toast(sim.dataset.simulate==='media'?'Media intake opened for the selected role.':'New briefing workspace opened.');return}
    });
    document.addEventListener('input',e=>{if(e.target.matches('[data-story-filter]'))filterStoryTable()});document.addEventListener('change',e=>{if(e.target.matches('[data-status-filter]'))filterStoryTable()});
    $('[data-story-form]').addEventListener('submit',e=>{e.preventDefault();saveStory(e.target)});
  }

  function toast(msg){const t=$('[data-newsroom-toast]');t.textContent=msg;t.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.classList.remove('show'),2300)}

  $('[data-login-form]').addEventListener('submit',e=>{e.preventDefault();const f=e.target;if(login(f.username.value,f.password.value)){init()}else{$('[data-login-error]').textContent='The username or password is not recognised.'}});
  init();
})();
